Repository coralproject/talk, pull requests merged in 2018-08, with the labels that each got.

#1775 Use scheduledDeletionDelayHours variable on hoc
  plugins/talk-plugin-profile-data/client/hocs/index.js
Labels: bug, enhancement

#1759 [next] Comments and Moderation
  package-lock.json
  package.json
  src/core/common/types.ts
  src/core/server/app/middleware/passport/oidc.ts
  src/core/server/graph/common/context.ts
  src/core/server/graph/management/context.ts
  src/core/server/graph/management/middleware.ts
  src/core/server/graph/tenant/context.ts
  src/core/server/graph/tenant/middleware.ts
  src/core/server/graph/tenant/mutators/comment.ts
  src/core/server/graph/tenant/resolvers/auth_integrations.ts
  src/core/server/graph/tenant/resolvers/auth_settings.ts
  src/core/server/graph/tenant/resolvers/facebook_auth_integration.ts
  src/core/server/graph/tenant/resolvers/google_auth_integration.ts
  src/core/server/graph/tenant/resolvers/local_auth_integration.ts
  src/core/server/graph/tenant/resolvers/oidc_auth_integration.ts
  src/core/server/graph/tenant/resolvers/sso_auth_integration.ts
  src/core/server/graph/tenant/schema/schema.graphql
  src/core/server/logger.ts
  src/core/server/models/actions.ts
  src/core/server/models/asset.ts
  src/core/server/models/comment.ts
  src/core/server/models/settings.ts
  src/core/server/models/tenant.ts
  src/core/server/models/user.ts
  src/core/server/services/comments/index.ts
  src/core/server/services/comments/moderation/index.ts
  src/core/server/services/comments/moderation/phases/assetClosed.spec.ts
  src/core/server/services/comments/moderation/phases/assetClosed.ts
  src/core/server/services/comments/moderation/phases/commentLength.ts
  src/core/server/services/comments/moderation/phases/commentingDisabled.ts
  src/core/server/services/comments/moderation/phases/index.ts
  src/core/server/services/comments/moderation/phases/karma.ts
  src/core/server/services/comments/moderation/phases/links.ts
  src/core/server/services/comments/moderation/phases/premod.ts
  src/core/server/services/comments/moderation/phases/spam.ts
  src/core/server/services/comments/moderation/phases/staff.ts
  src/core/server/services/comments/moderation/phases/wordlist.ts
  src/core/server/services/comments/moderation/wordlist.spec.ts
  src/core/server/services/comments/moderation/wordlist.ts
  src/core/server/services/users/karma.ts
  src/types/akismet-api.d.ts
Labels: enhancement, in progress

#1786 Case sensitive displayName Issue
  graph/loaders/users.js
Labels: bug

#1785 Comment Editing Passthrough
  graph/mutators/comment.js
  plugins/talk-plugin-akismet/server/hooks.js
  plugins/talk-plugin-toxic-comments/server/hooks.js
Labels: bug

#1790 Add version tip to docs
  docs/source/07-02-troubleshooting-tips.md
Labels: docs

#1760 [next] Templates
  DESIGN.md
  config/watcher.ts
  gulpfile.js
  package-lock.json
  package.json
  scripts/generateSchemaTypes.js
  src/core/build/createWebpackConfig.ts
  src/core/server/app/handlers/auth/local.ts
  src/core/server/app/handlers/embed/stream.ts
  src/core/server/app/index.ts
  src/core/server/app/middleware/notFound.ts
  src/core/server/app/middleware/serveStatic.ts
  src/core/server/app/middleware/tenant.ts
  src/core/server/app/router.ts
Labels: enhancement

#1797 [next] Perspective API Integration
  package-lock.json
  package.json
  scripts/generateSchemaTypes.js
  src/core/common/config.ts
  src/core/server/app/index.ts
  src/core/server/app/middleware/error.ts
  src/core/server/app/middleware/logging.ts
  src/core/server/app/middleware/passport/index.ts
  src/core/server/app/middleware/passport/oidc.ts
  src/core/server/graph/tenant/resolvers/auth_integrations.ts
  src/core/server/graph/tenant/schema/schema.graphql
  src/core/server/index.ts
  src/core/server/models/actions.ts
  src/core/server/models/comment.ts
  src/core/server/models/settings.ts
  src/core/server/models/tenant.ts
  src/core/server/services/comments/index.ts
  src/core/server/services/comments/moderation/index.spec.ts
  src/core/server/services/comments/moderation/index.ts
  src/core/server/services/comments/moderation/phases/assetClosed.ts
  src/core/server/services/comments/moderation/phases/commentLength.ts
  src/core/server/services/comments/moderation/phases/commentingDisabled.ts
  src/core/server/services/comments/moderation/phases/index.ts
  src/core/server/services/comments/moderation/phases/karma.ts
  src/core/server/services/comments/moderation/phases/links.ts
  src/core/server/services/comments/moderation/phases/premod.ts
  src/core/server/services/comments/moderation/phases/spam.ts
  src/core/server/services/comments/moderation/phases/staff.ts
  src/core/server/services/comments/moderation/phases/toxic.ts
  src/core/server/services/comments/moderation/phases/wordlist.ts
  src/core/server/services/tenant/cache/adapter.ts
  src/core/server/services/tenant/cache/index.ts
  src/core/server/services/users/karma.ts
Labels: enhancement

#1810 fix language detection in IE11 and Edge
  client/coral-framework/services/i18n.js
Labels: in review

#1817 Subscription Optimizations
  graph/subscriptions/index.js
Labels: bug

#1822 add german translation for sort-upvoted
  plugins/talk-plugin-sort-most-upvoted/client/translations.yml
Labels: i18n, in review

#1805 Adding more translations in some missing pages
  client/coral-admin/src/components/Forbidden.js
  client/coral-admin/src/components/ForgotPassword.js
  client/coral-admin/src/routes/Community/components/People.js
  client/coral-admin/src/routes/Configure/components/EmbedLink.js
  client/coral-admin/src/routes/Configure/components/Wordlist.js
  client/coral-admin/src/routes/Moderation/components/Story.js
  client/coral-framework/services/i18n.js
  locales/en.yml
  locales/pt_BR.yml
  plugins/talk-plugin-auth/client/translations.yml
  plugins/talk-plugin-featured-comments/client/translations.yml
  plugins/talk-plugin-ignore-user/client/translations.yml
  plugins/talk-plugin-local-auth/translations.yml
  plugins/talk-plugin-member-since/client/translations.yml
  plugins/talk-plugin-moderation-actions/client/translations.yml
  plugins/talk-plugin-profile-data/client/translations.yml
  plugins/talk-plugin-respect/client/translations.yml
  plugins/talk-plugin-sort-most-replied/client/translations.yml
  plugins/talk-plugin-sort-most-respected/client/translations.yml
  plugins/talk-plugin-sort-newest/client/translations.yml
  plugins/talk-plugin-sort-oldest/client/translations.yml
  plugins/talk-plugin-viewing-options/client/translations.yml
Labels: i18n, in review

#1831 Add missing translation
  locales/de.yml
  locales/en.yml
Labels: i18n
