Repository coralproject/talk, pull requests merged in 2018-05, with the labels that each got.

#1533 [GDPR] Username Change
  client/coral-embed-stream/src/tabs/profile/components/Profile.js
  client/coral-embed-stream/src/tabs/profile/containers/Profile.js
  client/coral-framework/utils/user.js
  perms/reducers/mutation.js
  plugin-api/beta/client/hocs/index.js
  plugins/talk-plugin-auth/client/index.js
  plugins/talk-plugin-auth/client/profile-settings/components/ChangePassword.css
  plugins/talk-plugin-auth/client/profile-settings/components/ChangePassword.js
  plugins/talk-plugin-auth/client/profile-settings/components/ChangeUsername.css
  plugins/talk-plugin-auth/client/profile-settings/components/ChangeUsername.js
  plugins/talk-plugin-auth/client/profile-settings/components/ChangeUsernameDialog.css
  plugins/talk-plugin-auth/client/profile-settings/components/ChangeUsernameDialog.js
  plugins/talk-plugin-auth/client/profile-settings/components/ErrorMessage.css
  plugins/talk-plugin-auth/client/profile-settings/components/Form.css
  plugins/talk-plugin-auth/client/profile-settings/components/Form.js
  plugins/talk-plugin-auth/client/profile-settings/components/InputField.css
  plugins/talk-plugin-auth/client/profile-settings/components/InputField.js
  plugins/talk-plugin-auth/client/profile-settings/containers/ChangeUsername.js
  plugins/talk-plugin-auth/client/translations.yml
  services/users.js
  test/server/services/users.js
Labels: enhancement, feature

#1557 Index Creation Patch
  models/schema/index.js
  plugin-api/beta/server/getReactionConfig.js
  services/mongoose.js
Labels: bug

#1559 CLI Fixes
  bin/cli
  bin/cli-settings
  bin/util.js
  package.json
  yarn.lock
Labels: bug

#1538 [GDPR] Change Email (Local)
  .gitignore
  client/coral-embed-stream/src/tabs/profile/containers/Profile.js
  client/coral-framework/graphql/fragments.js
  docs/_config.yml
  docs/source/03-08-gdpr.md
  docs/source/_data/plugins.yml
  docs/source/plugin/talk-plugin-local-auth.md
  docs/source/plugins/overview.md
  docs/source/plugins/plugins-directory.md
  docs/themes/coral/layout/plugins.swig
  docs/themes/coral/source/css/talk.scss
  docs/themes/coral/source/js/plugins.js
  locales/en.yml
  locales/es.yml
  plugin-api/beta/client/hocs/index.js
  plugins.default.json
  plugins/talk-plugin-auth/README.md
  plugins/talk-plugin-auth/client/translations.yml
  plugins/talk-plugin-facebook-auth/README.md
  plugins/talk-plugin-google-auth/README.md
  plugins/talk-plugin-local-auth/README.md
  plugins/talk-plugin-local-auth/client/.eslintrc.json
  plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.css
  plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
  plugins/talk-plugin-local-auth/client/components/ChangePassword.css
  plugins/talk-plugin-local-auth/client/components/ChangePassword.js
  plugins/talk-plugin-local-auth/client/components/ChangeUsernameContentDialog.css
  plugins/talk-plugin-local-auth/client/components/ChangeUsernameContentDialog.js
  plugins/talk-plugin-local-auth/client/components/ChangeUsernameDialog.css
  plugins/talk-plugin-local-auth/client/components/ChangeUsernameDialog.js
  plugins/talk-plugin-local-auth/client/components/ConfirmChangesDialog.css
  plugins/talk-plugin-local-auth/client/components/ConfirmChangesDialog.js
  plugins/talk-plugin-local-auth/client/components/ErrorMessage.css
  plugins/talk-plugin-local-auth/client/components/ErrorMessage.js
  plugins/talk-plugin-local-auth/client/components/InputField.css
  plugins/talk-plugin-local-auth/client/components/InputField.js
  plugins/talk-plugin-local-auth/client/components/Profile.css
  plugins/talk-plugin-local-auth/client/components/Profile.js
  plugins/talk-plugin-local-auth/client/containers/ChangePassword.js
  plugins/talk-plugin-local-auth/client/containers/Profile.js
  plugins/talk-plugin-local-auth/client/graphql.js
  plugins/talk-plugin-local-auth/client/hocs/index.js
  plugins/talk-plugin-local-auth/client/index.js
  plugins/talk-plugin-local-auth/client/translations.yml
  plugins/talk-plugin-local-auth/index.js
  plugins/talk-plugin-local-auth/server/errors.js
  plugins/talk-plugin-local-auth/server/mutators.js
  plugins/talk-plugin-local-auth/server/resolvers.js
  plugins/talk-plugin-local-auth/server/translations.yml
  plugins/talk-plugin-local-auth/server/typeDefs.graphql
  plugins/talk-plugin-local-auth/server/typeDefs.js
  plugins/talk-plugin-profile-data/README.md
  plugins/talk-plugin-profile-data/client/components/DeleteMyAccount.css
  plugins/talk-plugin-profile-data/client/components/DeleteMyAccount.js
  plugins/talk-plugin-profile-data/client/components/DeleteMyAccountDialog.js
  plugins/talk-plugin-profile-data/client/containers/DownloadCommentHistory.js
  plugins/talk-plugin-profile-data/client/graphql.js
  plugins/talk-plugin-profile-data/client/hocs/index.js
  services/users.js
Labels: feature

#1556 User detail refactor
  client/coral-admin/src/components/UserDetail.js
  client/coral-admin/src/graphql/index.js
  client/coral-framework/graphql/mutations.js
Labels: enhancement

#1569 Username Change Fixes
  plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
  plugins/talk-plugin-local-auth/client/components/ChangeUsernameContentDialog.js
  plugins/talk-plugin-local-auth/client/components/Profile.css
  plugins/talk-plugin-local-auth/client/components/Profile.js
  plugins/talk-plugin-local-auth/client/containers/Profile.js
  plugins/talk-plugin-local-auth/client/translations.yml
Labels: bug

#1572 CSV Copy Changes
  plugins/talk-plugin-profile-data/server/router.js
Labels: bug

#1573 Copy and bug fixes
  plugins/talk-plugin-local-auth/client/translations.yml
  plugins/talk-plugin-profile-data/client/components/AccountDeletionRequestedSign.js
  plugins/talk-plugin-profile-data/client/translations.yml
Labels: bug

#1571 Change Password Errors BUG
  plugins/talk-plugin-local-auth/client/components/ChangePassword.js
Labels: bug

#1584 Tracing
  middleware/trace.js
Labels: enhancement

#1586 Fixed bug with password form
  errors.js
  graph/mutators/user.js
  locales/en.yml
  plugins/talk-plugin-local-auth/client/components/ChangePassword.js
Labels: bug

#1587 Fixed email in use error
  plugins/talk-plugin-local-auth/server/mutators.js
Labels: bug

#1582 Settings Cache Refactor
  bin/cli-settings
  graph/loaders/assets.js
  graph/loaders/settings.js
  graph/mutators/user.js
  graph/resolvers/asset.js
  graph/resolvers/comment.js
  graph/resolvers/root_query.js
  graph/resolvers/util.js
  middleware/staticTemplate.js
  models/schema/asset.js
  models/schema/setting.js
  package.json
  plugins/talk-plugin-local-auth/server/mutators.js
  plugins/talk-plugin-notifications/server/util.js
  plugins/talk-plugin-profile-data/server/connect.js
  plugins/talk-plugin-profile-data/server/mutators.js
  services/assets.js
  services/cache.js
  services/comments.js
  services/domain_list.js
  services/moderation/index.js
  services/passport.js
  services/settings.js
  services/setup.js
  services/tags.js
  services/wordlist.js
  test/server/services/settings.js
  yarn.lock
Labels: bug

#1589 Fixes for notifications
  plugins/talk-plugin-notifications-category-reply/index.js
  plugins/talk-plugin-notifications/server/NotificationManager.js
Labels: bug

#1590 Exclude deleted comments
  client/coral-admin/src/components/CommentAnimatedEdit.js
  client/coral-admin/src/components/CommentDeletedTombstone.css
  client/coral-admin/src/components/CommentDeletedTombstone.js
  client/coral-admin/src/components/UserDetailComment.js
  client/coral-admin/src/routes/Moderation/components/Comment.css
  client/coral-admin/src/routes/Moderation/components/Comment.js
  client/coral-admin/src/routes/Moderation/containers/Moderation.js
  graph/loaders/comments.js
  graph/mutators/action.js
  graph/typeDefs.graphql
  services/comments.js
  services/tags.js
Labels: enhancement

#1592 Delete Fix
  graph/mutators/user.js
  plugins/talk-plugin-profile-data/client/components/DeleteMyAccount.js
Labels: bug

#1594 Fixed Ignore User Error
  plugins/talk-plugin-ignore-user/client/containers/IgnoreUserConfirmation.js
Labels: bug

#1600 CLI Fixes
  bin/cli-assets
  bin/cli-users
Labels: bug, enhancement

#1598 Fit Delete My Account modals on mobile
  plugins/talk-plugin-profile-data/client/components/DeleteMyAccountDialog.css
Labels: bug

#1603 Corrections and clarity
  docs/source/03-07-product-guide-trust.md
Labels: docs

#1613 Delete package-lock.json
  package-lock.json
Labels: bug

#1599 CSS and Template Fixes + Improvements
  client/coral-admin/src/components/App.css
  client/coral-admin/src/components/App.js
  middleware/staticTemplate.js
  package.json
  public/css/dev.css
  routes/dev/assets.js
  routes/dev/index.js
  services/assets.js
  views/admin.ejs
  views/api/graphiql.ejs
  views/dev/article.ejs
  views/dev/articles.ejs
  views/embed/stream.ejs
  views/login.ejs
  views/partials/account.ejs
  views/partials/custom-css.ejs
  views/partials/dev-nav.ejs
  views/partials/dev.ejs
  views/partials/head.ejs
  yarn.lock
Labels: bug

#1606 Disable autofocus on IOS Safari, prevent zoom on narrow screens
  plugins/talk-plugin-rich-text/client/components/Editor.css
  plugins/talk-plugin-rich-text/client/components/Editor.js
Labels: bug

#1604 Email Attach Fixes
  client/coral-framework/components/Popup.js
  plugins/talk-plugin-local-auth/client/actions.js
  plugins/talk-plugin-local-auth/client/components/AddEmailAddressDialog.js
  plugins/talk-plugin-local-auth/client/components/AddEmailContent.js
  plugins/talk-plugin-local-auth/client/constants.js
  plugins/talk-plugin-local-auth/client/containers/AddEmailAddressDialog.js
  plugins/talk-plugin-local-auth/client/index.js
  plugins/talk-plugin-local-auth/client/reducer.js
  plugins/talk-plugin-local-auth/index.js
  plugins/talk-plugin-local-auth/server/translations.yml
  plugins/talk-plugin-local-auth/translations.yml
Labels: bug

#1595 Fix My Profile story title link behavior
  client/coral-embed-stream/src/tabs/profile/components/Comment.css
  client/coral-embed-stream/src/tabs/profile/components/Comment.js
Labels: bug

#1621 MongoDB Indexes
  graph/loaders/settings.js
  graph/resolvers/comment.js
  models/schema/action.js
  models/schema/comment.js
  models/schema/setting.js
  models/schema/user.js
  plugin-api/beta/server/getReactionConfig.js
  services/settings.js
Labels: enhancement

#1624 Username change copy
  plugins/talk-plugin-local-auth/client/components/Profile.js
  plugins/talk-plugin-local-auth/translations.yml
Labels: bug

#1614 Add new slot 'commentTombstone'
  client/coral-embed-stream/src/tabs/stream/components/Comment.js
  client/coral-embed-stream/src/tabs/stream/components/CommentTombstone.js
  client/coral-embed-stream/src/tabs/stream/containers/Comment.js
  docs/source/api/slots.md
Labels: enhancement

#1607 External Signin for Admin
  client/coral-admin/src/components/External.css
  client/coral-admin/src/components/External.js
  client/coral-admin/src/components/SignIn.js
  client/coral-admin/src/containers/SignIn.js
  client/coral-auth-callback/src/index.js
  client/coral-framework/services/postMessage.js
  client/coral-framework/utils/index.js
  plugin-api/beta/client/utils/index.js
  plugins/talk-plugin-facebook-auth/client/actions.js
  plugins/talk-plugin-facebook-auth/client/index.js
  plugins/talk-plugin-google-auth/client/actions.js
  plugins/talk-plugin-google-auth/client/index.js
Labels: enhancement

#1627 Upgrade Mongoose
  .nsprc
  models/schema/user.js
  package.json
  services/actions.js
  services/mongoose.js
  yarn.lock
Labels: dev support, in progress

#1628 fix optimisticResponse typo
  client/coral-framework/graphql/mutations.js
Labels: bug

#1629 RTE Bugfixes
  plugins/talk-plugin-rich-text/client/components/rte/components/Button.js
  plugins/talk-plugin-rich-text/client/components/rte/factories/createToggle.js
  plugins/talk-plugin-rich-text/client/components/rte/lib/dom.js
Labels: bug

#1632 Only display paragraph if delete requested
  plugins/talk-plugin-profile-data/client/components/DeleteMyAccount.js
Labels: bug

#1635 German translations for v4.4.1
  locales/de.yml
  plugins/talk-plugin-local-auth/translations.yml
  plugins/talk-plugin-profile-data/client/translations.yml
  plugins/talk-plugin-profile-data/translations.yml
Labels: i18n, in review

#1634 Show overflow text on download comments button when disabled
  plugins/talk-plugin-profile-data/client/components/DownloadCommentHistory.css
Labels: in review

#1625 Displaying multiple external provider IDs
  client/coral-admin/src/components/UserDetail.css
  client/coral-admin/src/components/UserDetail.js
  client/coral-admin/src/containers/UserDetail.js
  client/coral-admin/src/routes/Community/components/People.js
  locales/en.yml
Labels: enhancement

#1633 Content Security Policy + Nunjacks
  app.js
  config.js
  docs/source/02-02-advanced-configuration.md
  middleware/contentSecurityPolicy.js
  middleware/nonce.js
  package.json
  plugins/talk-plugin-notifications/server/router.js
  plugins/talk-plugin-notifications/server/views/unsubscribe-notifications.ejs
  plugins/talk-plugin-notifications/server/views/unsubscribe-notifications.njk
  plugins/talk-plugin-profile-data/server/router.js
  plugins/talk-plugin-profile-data/server/views/download.ejs
  plugins/talk-plugin-profile-data/server/views/download.njk
  routes/account/index.js
  routes/admin/index.js
  routes/api/v1/csp.js
  routes/api/v1/graph.js
  routes/api/v1/index.js
  routes/dev/assets.js
  routes/dev/index.js
  routes/embed/index.js
  routes/index.js
  routes/login/index.js
  routes/plugins.js
  services/passport.js
  views/account/email/confirm.ejs
  views/account/email/confirm.njk
  views/account/password/reset.ejs
  views/account/password/reset.njk
  views/admin.ejs
  views/admin.njk
  views/api/graphiql.ejs
  views/api/graphiql.njk
  views/auth-callback.ejs
  views/auth-callback.njk
  views/dev/article.ejs
  views/dev/article.njk
  views/dev/articles.ejs
  views/dev/articles.njk
  views/embed/stream.ejs
  views/embed/stream.njk
  views/login.ejs
  views/login.njk
  views/partials/account.ejs
  views/partials/custom-css.ejs
  views/partials/custom-css.njk
  views/partials/data.ejs
  views/partials/data.njk
  views/partials/dev-nav.ejs
  views/partials/favicon.njk
  views/partials/head.ejs
  views/partials/nav.njk
  views/templates/account.njk
  views/templates/base.njk
  views/templates/development.njk
  yarn.lock
Labels: enhancement

#1642 [Doc] Fix incorrect statement regarding GDPR
  docs/source/03-08-gdpr.md
Labels: in review

#1644 add from to import statement
  docs/source/api/client.md
Labels: docs

#1640 Remove wordbreak
  client/coral-admin/src/routes/Moderation/components/Comment.css
Labels: in review

#1654 Enhanced documentation on JWT's
  docs/source/02-01-required-configuration.md
  docs/source/integrating/authentication.md
  docs/themes/coral/source/css/talk.scss
Labels: docs, enhancement

#1655 Added missing translation
  locales/en.yml
Labels: bug

#1653 Add missing translations (en/de) for plugins ignore-user and local-auth.
  plugins/talk-plugin-ignore-user/client/translations.yml
  plugins/talk-plugin-local-auth/client/components/ChangePassword.js
  plugins/talk-plugin-local-auth/client/components/ChangeUsernameContentDialog.js
  plugins/talk-plugin-local-auth/translations.yml
  services/mailer/templates/password-reset.txt.ejs
Labels: i18n

#1656 Disable CSP
  docs/source/02-02-advanced-configuration.md
  routes/index.js
  routes/plugins.js
Labels: enhancement

#1630 Karma Score
  client/coral-admin/src/components/ApproveButton.js
  client/coral-admin/src/components/CommentLabels.js
  client/coral-admin/src/components/KarmaTooltip.css
  client/coral-admin/src/components/KarmaTooltip.js
  client/coral-admin/src/components/RejectButton.js
  client/coral-admin/src/components/UserDetail.css
  client/coral-admin/src/components/UserDetail.js
  client/coral-admin/src/containers/UserDetail.js
  client/coral-admin/src/graphql/index.js
  client/coral-admin/src/routes/Moderation/components/ModerationMenu.js
  client/coral-admin/src/routes/Moderation/components/ModerationQueue.js
  client/coral-framework/helpers/webpackGlobals.js
  client/coral-framework/utils/user.js
  docs/source/03-07-product-guide-trust.md
  graph/resolvers/index.js
  graph/resolvers/karma_threshold.js
  graph/resolvers/settings.js
  graph/typeDefs.graphql
  locales/ar.yml
  locales/da.yml
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/fi_FI.yml
  locales/fr.yml
  locales/nl_NL.yml
  locales/pt_BR.yml
  locales/zh_CN.yml
  locales/zh_TW.yml
  middleware/nonce.js
  middleware/staticTemplate.js
  routes/api/v1/csp.js
  services/karma.js
  services/moderation/phases/karma.js
  test/e2e/globals.js
  test/e2e/page_objects/admin.js
  test/e2e/specs/03_embedStream.js
  test/e2e/specs/05_banUser.js
  test/e2e/specs/06_suspendUser.js
  test/server/services/karma.js
  webpack.config.js
Labels: bug, enhancement

#1666 Fixed double encoding
  views/auth-callback.njk
Labels: bug

#1670 Custom CSS Fix
  views/embed/stream.njk
  views/login.njk
  views/templates/account.njk
  views/templates/base.njk
Labels: bug

#1668 Translation Fixes
  plugins/talk-plugin-auth/client/translations.yml
  plugins/talk-plugin-local-auth/translations.yml
Labels: bug

#1528 Check if token is in localStorage before logout
  client/coral-framework/actions/auth.js
  middleware/authorization.js
Labels: in review
