Repository coralproject/talk, pull requests merged in 2018-09, with the labels that each got.

#1839 Change proxy-agent to support http/https through http/https/socks/pac…
  jobs/scraper/index.js
  package.json
  yarn.lock
Labels: in review

#1840 fix long urls breaking moderation box
  client/coral-admin/src/routes/Moderation/components/Comment.css
Labels: bug, in review

#1841 moderation: toggle comment date from timeago to full date
  client/coral-admin/src/components/UserDetailComment.js
  client/coral-admin/src/routes/Moderation/components/Comment.js
  client/coral-framework/components/CommentTimestamp.js
  client/coral-framework/components/TimeAgo.css
  client/coral-framework/components/TimeAgo.js
Labels: feature idea, in review

#1860 Improved Comment URL Handling
  client/coral-admin/src/actions/community.js
  client/coral-admin/src/actions/stories.js
  client/coral-admin/src/components/UserDetailComment.js
  client/coral-admin/src/routes/Moderation/components/Comment.js
  client/coral-embed-stream/src/actions/stream.js
  client/coral-embed-stream/src/tabs/profile/components/Comment.js
  client/coral-embed/src/Stream.js
  client/coral-framework/constants/url.js
  client/coral-framework/utils/index.js
  client/coral-framework/utils/url.js
  package.json
  plugin-api/beta/client/utils/index.js
  plugins/talk-plugin-permalink/client/components/PermalinkButton.js
  yarn.lock
Labels: bug

#1870 Tag Fix
  services/tags.js
  test/server/services/tags.js
Labels: bug

#1878 Shorten es.yml translation to "Configurar"
  locales/es.yml
Labels: i18n

#1879 Add missing Spanish translations for local-auth
  package.json
  plugins/talk-plugin-local-auth/translations.yml
Labels: i18n

#1872 Adds Spanish translations for profile data
  plugins/talk-plugin-profile-data/translations.yml
Labels: i18n

#1880 Es typo
  plugins/talk-plugin-local-auth/translations.yml
Labels: i18n

#1889 More profile-data plugin es translations
  plugins/talk-plugin-profile-data/client/translations.yml
Labels: i18n

#1887 Update es translations for ignore-user plugin
  plugins/talk-plugin-ignore-user/client/translations.yml
Labels: i18n

#1893 Shorten Spanish phrases for UI purposes
  locales/es.yml
  plugins/talk-plugin-featured-comments/client/translations.yml
  plugins/talk-plugin-viewing-options/client/translations.yml
Labels: i18n
