Repository coralproject/talk, pull requests merged in 2018-03, with the labels that each got.

#1409 Featured Notifications
  .circleci/config.yml
  .gitignore
  docs/_docs/04-03-additional-plugins.md
  jest.config.js
  package.json
  plugins/talk-plugin-notifications-category-featured/client/.eslintrc.json
  plugins/talk-plugin-notifications-category-featured/client/containers/Toggle.js
  plugins/talk-plugin-notifications-category-featured/client/graphql.js
  plugins/talk-plugin-notifications-category-featured/client/index.js
  plugins/talk-plugin-notifications-category-featured/client/translations.yml
  plugins/talk-plugin-notifications-category-featured/index.js
  plugins/talk-plugin-notifications-category-featured/translations.yml
  plugins/talk-plugin-notifications-category-reply/.eslintrc.json
  plugins/talk-plugin-notifications-category-reply/translations.yml
  plugins/talk-plugin-notifications/.eslintrc.json
  plugins/talk-plugin-notifications/client/containers/Settings.js
  yarn.lock
Labels: enhancement

#1410 Staff Reply Notifications
  .gitignore
  plugins/talk-plugin-notifications-category-reply/translations.yml
  plugins/talk-plugin-notifications-category-staff/client/.eslintrc.json
  plugins/talk-plugin-notifications-category-staff/client/containers/Toggle.js
  plugins/talk-plugin-notifications-category-staff/client/graphql.js
  plugins/talk-plugin-notifications-category-staff/client/index.js
  plugins/talk-plugin-notifications-category-staff/client/translations.yml
  plugins/talk-plugin-notifications-category-staff/index.js
  plugins/talk-plugin-notifications-category-staff/translations.yml
  plugins/talk-plugin-notifications/server/NotificationManager.js
Labels: enhancement

#1412 CI Fixes
  README.md
  scripts/docker.sh
Labels: bug

#1413 Email Confirmation Notifications
  client/coral-ui/components/Checkbox.css
  client/coral-ui/components/Spinner.js
  config.js
  docs/_docs/02-02-advanced-configuration.md
  docs/_docs/04-03-additional-plugins.md
  graph/mutators/comment.js
  graph/resolvers/index.js
  graph/resolvers/local_user_profile.js
  graph/resolvers/user_profile.js
  graph/typeDefs.graphql
  plugins/talk-plugin-auth/client/login/containers/ResendEmailConfirmation.js
  plugins/talk-plugin-notifications-category-featured/client/containers/Toggle.js
  plugins/talk-plugin-notifications-category-featured/index.js
  plugins/talk-plugin-notifications-category-reply/client/containers/Toggle.js
  plugins/talk-plugin-notifications-category-reply/index.js
  plugins/talk-plugin-notifications-category-staff/client/containers/Toggle.js
  plugins/talk-plugin-notifications-category-staff/index.js
  plugins/talk-plugin-notifications/client/components/Banner.css
  plugins/talk-plugin-notifications/client/components/Banner.js
  plugins/talk-plugin-notifications/client/components/EmailVerificationBanner.css
  plugins/talk-plugin-notifications/client/components/EmailVerificationBanner.js
  plugins/talk-plugin-notifications/client/components/Settings.css
  plugins/talk-plugin-notifications/client/components/Settings.js
  plugins/talk-plugin-notifications/client/components/Toggle.css
  plugins/talk-plugin-notifications/client/components/Toggle.js
  plugins/talk-plugin-notifications/client/containers/EmailVerificationBanner.js
  plugins/talk-plugin-notifications/client/containers/Settings.js
  plugins/talk-plugin-notifications/client/translations.yml
  plugins/talk-plugin-notifications/server/NotificationManager.js
  plugins/talk-plugin-notifications/server/config.js
  plugins/talk-plugin-notifications/server/resolvers.js
  plugins/talk-plugin-notifications/server/typeDefs.graphql
  services/logging.js
Labels: enhancement

#1418 Scrape Asset GraphQL Mutation
  Dockerfile
  config.js
  graph/mutators/asset.js
  graph/resolvers/root_mutation.js
  graph/typeDefs.graphql
  routes/api/v1/index.js
  scripts/docker.sh
Labels: enhancement

#1420 Workspace + Plugin Regression
  Dockerfile.onbuild
Labels: bug

#1425 Scraping Fixes
  graph/context.js
  graph/loaders/assets.js
  graph/mutators/asset.js
  jobs/index.js
  jobs/scraper.js
  services/logging.js
  services/scraper.js
Labels: bug

#1419 Notification Digesting
  .gitignore
  client/coral-admin/src/routes/Community/components/People.css
  client/coral-admin/src/routes/Community/components/People.js
  client/coral-admin/src/routes/Stories/components/Stories.css
  client/coral-admin/src/routes/Stories/components/Stories.js
  client/coral-framework/components/TalkProvider.js
  client/coral-framework/hocs/index.js
  client/coral-framework/hocs/withEnumValues.js
  client/coral-framework/services/introspection.js
  client/coral-ui/components/Dropdown.css
  client/coral-ui/components/Dropdown.js
  client/coral-ui/components/Option.css
  plugin-api/beta/client/hocs/index.js
  plugins/talk-plugin-notifications-category-featured/index.js
  plugins/talk-plugin-notifications-category-featured/translations.yml
  plugins/talk-plugin-notifications-category-reply/index.js
  plugins/talk-plugin-notifications-category-staff/index.js
  plugins/talk-plugin-notifications-digest-daily/client/.eslintrc.json
  plugins/talk-plugin-notifications-digest-daily/client/index.js
  plugins/talk-plugin-notifications-digest-daily/client/translations.yml
  plugins/talk-plugin-notifications-digest-daily/index.js
  plugins/talk-plugin-notifications-digest-hourly/client/.eslintrc.json
  plugins/talk-plugin-notifications-digest-hourly/client/index.js
  plugins/talk-plugin-notifications-digest-hourly/client/translations.yml
  plugins/talk-plugin-notifications-digest-hourly/index.js
  plugins/talk-plugin-notifications/client/components/Settings.css
  plugins/talk-plugin-notifications/client/components/Settings.js
  plugins/talk-plugin-notifications/client/containers/Settings.js
  plugins/talk-plugin-notifications/client/graphql.js
  plugins/talk-plugin-notifications/client/translations.yml
  plugins/talk-plugin-notifications/package.json
  plugins/talk-plugin-notifications/server/NotificationManager.js
  plugins/talk-plugin-notifications/server/connect.js
  plugins/talk-plugin-notifications/server/digests.js
  plugins/talk-plugin-notifications/server/emails/notification-digest.html.ejs
  plugins/talk-plugin-notifications/server/emails/notification-digest.txt.ejs
  plugins/talk-plugin-notifications/server/hooks.js
  plugins/talk-plugin-notifications/server/index.js
  plugins/talk-plugin-notifications/server/messages.js
  plugins/talk-plugin-notifications/server/resolvers.js
  plugins/talk-plugin-notifications/server/translations.yml
  plugins/talk-plugin-notifications/server/typeDefs.graphql
  plugins/talk-plugin-notifications/server/util.js
  yarn.lock
Labels: enhancement

#1431 Updated coralproject.github.io links to docs.coralproject.net
  bin/templates/plugin/client/components/MyPluginComponent.js
  bin/templates/plugin/client/index.js
  docs/source/01-01-talk-quickstart.md
  errors.js
Labels: bug

#1443 Integration Fixes
  .circleci/config.yml
  .circleci/e2e.sh
  nightwatch-browserstack.conf.js
  nightwatch.conf.js
Labels: bug

#1433 Arabic Translation
  client/coral-framework/services/i18n.js
  locales/ar.yml
  plugins/talk-plugin-akismet/client/translations.yml
  plugins/talk-plugin-auth/client/translations.yml
  plugins/talk-plugin-author-menu/client/translations.yml
  plugins/talk-plugin-facebook-auth/client/translations.yml
  plugins/talk-plugin-featured-comments/client/translations.yml
  plugins/talk-plugin-flag-details/client/translations.yml
  plugins/talk-plugin-google-auth/client/translations.yml
  plugins/talk-plugin-ignore-user/client/translations.yml
  plugins/talk-plugin-like/client/translations.yml
  plugins/talk-plugin-love/client/translations.yml
  plugins/talk-plugin-member-since/client/translations.yml
  plugins/talk-plugin-moderation-actions/client/translations.yml
  plugins/talk-plugin-offtopic/client/translations.json
  plugins/talk-plugin-profile-settings/client/translations.yml
  plugins/talk-plugin-respect/client/translations.yml
  plugins/talk-plugin-sort-most-liked/client/translations.yml
  plugins/talk-plugin-sort-most-loved/client/translations.yml
  plugins/talk-plugin-sort-most-replied/client/translations.yml
  plugins/talk-plugin-sort-most-respected/client/translations.yml
  plugins/talk-plugin-sort-newest/client/translations.yml
  plugins/talk-plugin-sort-oldest/client/translations.yml
  plugins/talk-plugin-subscriber/client/translations.yml
  plugins/talk-plugin-toxic-comments/client/translations.yml
  plugins/talk-plugin-viewing-options/client/translations.yml
Labels: i18n

#1432 Restored User Creation CLI
  bin/cli-users
Labels: cli, enhancement

#1445 Slack plugin fix
  plugins/talk-plugin-slack-notifications/server/hooks.js
Labels: bug

#1435 Rich Text Plugin Upgrade - Escaping <blockquote>
  plugins/talk-plugin-rich-text-pell/package.json
  yarn.lock
Labels: plugin support

#1439 Job Separation
  bin/cli-serve
  bin/util.js
  jobs/index.js
  jobs/mailer.js
  plugins/talk-plugin-notifications/server/NotificationManager.js
  serve.js
Labels: enhancement

#1438 Adding Plugin Tutorials to Docs
  docs/_config.yml
  docs/source/05-01-building-basic-plugin.md
  docs/source/05-02-customizing-plugins-coral-ui.md
  docs/source/07-01-faq.md
  docs/source/images/pride_reaction_tutorial_1.png
  docs/source/images/pride_reaction_tutorial_2.png
  docs/source/images/pride_reaction_tutorial_3.png
  docs/source/images/pride_reaction_tutorial_4.png
  docs/source/images/pride_reaction_tutorial_5.png
  docs/source/images/pride_reaction_tutorial_6.png
  docs/source/images/pride_reaction_tutorial_7.png
  docs/themes/coral/source/css/talk.scss
Labels: docs

#1427 checks for and mitigates username collisions with new external users
  services/users.js
  test/server/services/users.js
Labels: bug

#1442 Use asset.url as a fallback when asset.title is missing
  client/coral-admin/src/components/UserDetailComment.js
  client/coral-admin/src/routes/Moderation/components/Comment.js
Labels: enhancement, in review

#1447 Logout Fix
  .gitignore
  routes/api/v1/auth.js
  services/passport.js
Labels: bug

#1440 User Delete
  bin/cli-users
  graph/mutators/user.js
  graph/resolvers/root_mutation.js
  graph/typeDefs.graphql
  perms/constants/mutation.js
Labels: cli, enhancement

#1441 Restore the userCreated event
  bin/cli-setup
  docs/source/reference/server.md
  graph/subscriptions/setupFunctions.js
  graph/typeDefs.graphql
  perms/constants/subscription.js
  perms/reducers/subscription.js
  plugins/talk-plugin-facebook-auth/server/passport.js
  plugins/talk-plugin-google-auth/server/passport.js
  routes/api/v1/setup.js
  routes/api/v1/users.js
  services/setup.js
  services/users.js
  test/server/graph/mutations/changeUsername.js
  test/server/graph/mutations/editComment.js
  test/server/graph/mutations/ignoreUser.js
  test/server/graph/mutations/setUserBanStatus.js
  test/server/graph/mutations/setUserSuspensionStatus.js
  test/server/graph/mutations/setUserUsernameStatus.js
  test/server/graph/queries/asset.js
  test/server/graph/queries/user.js
  test/server/routes/api/auth/index.js
  test/server/routes/api/user/index.js
  test/server/services/comments.js
  test/server/services/tags.js
  test/server/services/tokens.js
  test/server/services/users.js
Labels: bug, enhancement

#1451 Asset Manager Tutorial
  docs/_config.yml
  docs/source/integrating/asset-management.md
Labels: docs

#1449 Fix rainbow emoji, add name of Part 2 tutorial
  docs/source/05-01-building-basic-plugin.md
Labels: docs

#1436 Upgrade for Debug Tools for Slots and Plugins
  client/coral-embed-stream/src/reducers/configure.js
  client/coral-embed-stream/src/tabs/stream/containers/Stream.js
  client/coral-embed/src/Stream.js
  client/coral-embed/src/StreamInterface.js
  client/coral-framework/actions/config.js
  client/coral-framework/components/Slot.css
  client/coral-framework/components/Slot.js
  client/coral-framework/constants/config.js
  client/coral-framework/hocs/withSlotElements.js
  client/coral-framework/reducers/config.js
  client/coral-framework/services/bootstrap.js
  client/coral-framework/services/plugins.js
  docs/_config.yml
  docs/source/04-06-slots-and-plugins.md
  plugin-api/beta/client/selectors/index.js
  views/article.ejs
Labels: docs, in progress

#1452 Context Performance
  graph/context.js
  services/logging.js
Labels: enhancement

#1466 Moved extract-text-webpack-plugin from devDependencies to dependencies
  package.json
Labels: bug

#1465 Mailer Template Fix
  services/mailer/templates.js
Labels: bug

#1467 Fixed misplaced deps
  .babelrc
  package.json
  routes/index.js
Labels: bug

#1468 Updated Notifications Docs
  plugins/talk-plugin-notifications/README.md
Labels: docs

#1463 Update default plugins
  config.js
  docs/source/_data/plugins.yml
  plugins.default.json
Labels: plugin support

#1473 Email Verification Copy
  errors.js
  locales/en.yml
  routes/api/v1/account.js
  services/users.js
Labels: bug

#1479 Markdown Editor Fixes
  .nodemon.json
  client/coral-embed-stream/src/tabs/configure/components/QuestionBoxBuilder.js
  client/coral-framework/components/MarkdownEditor.js
  client/coral-framework/components/loadable/MarkdownEditor.css
  client/coral-framework/components/loadable/MarkdownEditor.js
  docs/.gitignore
  docs/source/api/graphql.md
  middleware/staticTemplate.js
  package.json
  scripts/generateIntrospectionResult.js
  webpack.config.js
  yarn.lock
Labels: bug

#1476 Create 'when you've installed talk' tutorial
  docs/_config.yml
  docs/source/05-03-when-youve-installed-talk.md
Labels: docs

#1464 Docs for the Plugins API
  docs/_config.yml
  docs/source/05-03-when-youve-installed-talk.md
  docs/source/api/client.md
  docs/source/api/slots.md
Labels: docs, in progress

#1483 Email Subject Docs
  plugins/talk-plugin-notifications/README.md
Labels: docs

#1482 Introspection fix
  scripts/generateIntrospectionResult.js
Labels: bug

#1488 Notification fixes
  plugins/talk-plugin-notifications-category-reply/index.js
  plugins/talk-plugin-notifications-category-staff/index.js
  plugins/talk-plugin-notifications/server/messages.js
Labels: bug

#1486 Docs Link Fixes
  docs/_config.yml
  docs/source/01-01-talk-quickstart.md
  docs/source/01-02-installation-from-docker.md
  docs/source/01-03-installation-from-source.md
  docs/source/02-01-required-configuration.md
  docs/source/02-02-advanced-configuration.md
  docs/source/03-01-product-guide-how-talk-works.md
  docs/source/03-02-product-guide-commenter-features.md
  docs/source/03-03-product-guide-moderator-features.md
  docs/source/03-04-product-guide-trust.md
  docs/source/03-05-product-guide-toxic-comments.md
  docs/source/plugins/overview.md
  docs/themes/coral/layout/partial/sidebar.swig
  plugins/talk-plugin-toxic-comments/README.md
Labels: docs

#1490 Plugin Docs Update
  docs/source/_data/plugins.yml
Labels: docs
