Repository coralproject/talk, pull requests merged in 2018-10, with the labels that each got.

#1954 Static URI + Social Callback bug
  package.json
  services/passport.js
Labels: bug

#1955 Passport Fix
  client/coral-auth-callback/src/index.js
  client/coral-framework/services/bootstrap.js
  middleware/staticTemplate.js
  services/passport.js
  url.js
Labels: bug

#1959 Viewport Height
  client/coral-embed-stream/src/tabs/stream/components/Stream.css
Labels: bug

#1968 [next] Comments Count
  src/core/client/stream/components/App.spec.tsx
  src/core/client/stream/components/App.tsx
  src/core/client/stream/components/CommentCountTab.tsx
  src/core/client/stream/components/__snapshots__/App.spec.tsx.snap
  src/core/client/stream/containers/AppContainer.tsx
  src/core/client/stream/containers/CommentsCountContainer.tsx
  src/core/client/stream/mutations/CreateCommentMutation.ts
  src/core/client/stream/queries/CommentsCountQuery.tsx
  src/core/client/stream/queries/IfLoggedInQuery.tsx
  src/core/client/stream/test/comments/__snapshots__/editComment.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/loadMore.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/permalinkView.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/permalinkViewAssetNotFound.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/permalinkViewCommentNotFound.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/postComment.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/postReply.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/renderReplies.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/renderStream.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/showAllReplies.spec.tsx.snap
  src/core/client/stream/test/comments/__snapshots__/showConversation.spec.tsx.snap
  src/core/client/stream/test/create.tsx
  src/core/client/stream/test/fixtures.ts
  src/locales/en-US/stream.ftl
Labels: don't merge

#1977 Fix spanish translation
  plugins/talk-plugin-toxic-comments/client/translations.yml
Labels: i18n

#1971 Websocket Regression
  client/coral-framework/actions/auth.js
  client/coral-framework/services/client.js
  package.json
  yarn.lock
Labels: bug

#1986 Fixed typo in GDPR docs.
  docs/source/03-08-gdpr.md
Labels: docs

#1976 do not show admin drawer unless user has access
  client/coral-admin/src/components/Drawer.js
  test/e2e/page_objects/admin.js
  test/e2e/specs/02_admin.js
Labels: in review

#1999 Perspective API documentation update
  plugins/talk-plugin-toxic-comments/README.md
Labels: docs

#2011 Email Prefix Fix
  config.js
Labels: bug

#2006 Keep Question Box visible after stream is closed #1939
  client/coral-embed-stream/src/tabs/stream/components/Stream.js
Labels: in review

#1990 Display avatar left of comments by default
  client/coral-embed-stream/src/tabs/stream/components/Comment.css
  client/coral-embed-stream/style/default.css
Labels: in review

#2014 Made Banned/Suspended Word Lists collapsible in Admin > Configure
  client/coral-admin/src/routes/Configure/components/Wordlist.js
  client/coral-framework/components/ConfigureCard.css
  client/coral-framework/components/ConfigureCard.js
Labels: in review

#1963 Update text and description in moderation configure view
  client/coral-admin/src/routes/Configure/components/StreamSettings.js
  locales/ar.yml
  locales/da.yml
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/fi_FI.yml
  locales/fr.yml
  locales/nl_NL.yml
  locales/pt_BR.yml
  locales/zh_CN.yml
  locales/zh_TW.yml
Labels: in review

#2018 Consistency Improvements
  client/coral-framework/actions/auth.js
  client/coral-framework/services/auth.js
  client/coral-framework/services/bootstrap.js
  plugins/talk-plugin-toxic-comments/server/perspective.js
  services/moderation/phases/links.js
  views/account/password/reset.njk
Labels: bug

#2049 Typo Fix
  jobs/scraper/index.js
Labels: bug

#2051 i18n support for Edit link
  client/coral-embed-stream/src/tabs/stream/components/Comment.js
  locales/en.yml
  locales/es.yml
Labels: i18n

#2032 Add italian translation
  client/coral-framework/services/i18n.js
  locales/it.yml
Labels: in review

#2047 Spanish translation tweak #1
  plugins/talk-plugin-auth/client/translations.yml
Labels: i18n

#2036 Document CLI tools as many people don't know about this #1941
  docs/_config.yml
  docs/source/02-03-cli-tools.md
Labels: in review
