Repository coralproject/talk, pull requests merged in 2018-12, with the labels that each got.

#2105 Docs update
  docs/source/01-01-talk-quickstart.md
  docs/source/01-03-installation-from-source.md
  docs/source/01-05-pre-launch-checklist.md
  docs/source/03-02-product-guide-commenter-features.md
  docs/source/integrating/asset-management.md
  docs/source/integrating/authentication.md
  docs/source/plugins/overview.md
Labels: docs

#2119 CDN + Observabilities fixes
  client/coral-embed/src/Stream.js
  config.js
  middleware/trace.js
  package.json
  routes/index.js
  yarn.lock
Labels: bug

#2117 [next] Resolved Race Conditions
  src/core/server/graph/tenant/loaders/Comments.ts
  src/core/server/graph/tenant/loaders/Stories.ts
  src/core/server/graph/tenant/loaders/util.ts
  src/core/server/graph/tenant/resolvers/Query.ts
Labels: bug

#2126 Add Documentation Redirect - asset management to cms integration
  docs/public/_redirects
Labels: docs

#2128 fix minor ui/css bug in moderation/comment component caused by long links
  client/coral-admin/src/routes/Moderation/components/Comment.css
Labels: bug, in review
