Repository coralproject/talk, pull requests merged in 2018-07, with the labels that each got.

#1731 Watcher --only
  scripts/watcher/bin/watcher.ts
  scripts/watcher/types.ts
  scripts/watcher/watch.ts
Labels: enhancement

#1732 Onbuild Polyfill
  Dockerfile.onbuild
  docs/source/02-02-advanced-configuration.md
Labels: bug

#1721 [Request for feedback] Heroku fix
  package-lock.json
  services/env.js
Labels: in review

#1737 findOrCreateExternalUser Deprecation
  docs/_config.yml
  docs/source/06-03-migrating-from-3.md
  docs/source/api/server.md
  plugins/talk-plugin-facebook-auth/server/passport.js
  plugins/talk-plugin-google-auth/server/passport.js
  services/users.js
Labels: bug, enhancement

#1740 Add suggested index to comments
  models/schema/comment.js
Labels: enhancement

#1739 updated translation files with new Arabic translations
  locales/ar.yml
  plugins/talk-plugin-auth/client/translations.yml
  plugins/talk-plugin-ignore-user/client/translations.yml
  plugins/talk-plugin-local-auth/translations.yml
  plugins/talk-plugin-notifications-category-featured/client/translations.yml
  plugins/talk-plugin-notifications-category-featured/translations.yml
  plugins/talk-plugin-notifications-category-reply/client/translations.yml
  plugins/talk-plugin-notifications-category-reply/translations.yml
  plugins/talk-plugin-notifications-category-staff/client/translations.yml
  plugins/talk-plugin-notifications-category-staff/translations.yml
  plugins/talk-plugin-notifications-digest-daily/client/translations.yml
  plugins/talk-plugin-notifications-digest-hourly/client/translations.yml
  plugins/talk-plugin-notifications/client/translations.yml
  plugins/talk-plugin-notifications/server/translations.yml
  plugins/talk-plugin-profile-data/client/translations.yml
  plugins/talk-plugin-profile-data/translations.yml
Labels: in review

#1742 Add FAQ and Troubleshooting docs
  docs/_config.yml
  docs/source/07-01-faq.md
  docs/source/07-02-troubleshooting-tips.md
  docs/source/integrating/styling-css.md
Labels: docs

#1764 Username Status Fix
  package.json
  services/users.js
Labels: bug
