Repository coralproject/talk, pull requests merged in 2018-06, with the labels that each got.

#1671 GraphiQL Fixes
  views/api/graphiql.njk
Labels: bug

#1672 Humanized Karma
  client/coral-admin/src/components/CountBadge.js
  client/coral-admin/src/components/UserDetail.js
  client/coral-framework/helpers/numbers.js
Labels: enhancement

#1673 Use Markdown for the "asset is closed" message.
  client/coral-admin/src/routes/Configure/components/StreamSettings.js
  client/coral-embed-stream/src/tabs/stream/components/Stream.js
Labels: in review

#1676 Added .nvmrc file
  .nvmrc
Labels: enhancement

#1636 Introduce final form, i18n helper, validators and refactor AddEmailAddress
  client/coral-framework/lib/validation.js
  locales/ar.yml
  locales/da.yml
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/fi_FI.yml
  locales/fr.yml
  locales/nl_NL.yml
  locales/pt_BR.yml
  locales/zh_CN.yml
  locales/zh_TW.yml
  package.json
  plugin-api/beta/client/lib/validation.js
  plugins/talk-plugin-local-auth/client/components/AddEmailAddress/AddEmailForm.css
  plugins/talk-plugin-local-auth/client/components/AddEmailAddress/AddEmailForm.js
  plugins/talk-plugin-local-auth/client/components/AddEmailAddress/Dialog.css
  plugins/talk-plugin-local-auth/client/components/AddEmailAddress/Dialog.js
  plugins/talk-plugin-local-auth/client/components/AddEmailAddress/EmailAddressAdded.css
  plugins/talk-plugin-local-auth/client/components/AddEmailAddress/EmailAddressAdded.js
  plugins/talk-plugin-local-auth/client/components/AddEmailAddress/VerifyEmailAddress.css
  plugins/talk-plugin-local-auth/client/components/AddEmailAddress/VerifyEmailAddress.js
  plugins/talk-plugin-local-auth/client/components/AddEmailAddress/index.js
  plugins/talk-plugin-local-auth/client/components/AddEmailAddressDialog.js
  plugins/talk-plugin-local-auth/client/components/AddEmailContent.js
  plugins/talk-plugin-local-auth/client/components/InputField.js
  plugins/talk-plugin-local-auth/client/components/Label.js
  plugins/talk-plugin-local-auth/client/containers/AddEmailAddressDialog.js
  plugins/talk-plugin-local-auth/translations.yml
  scripts/i18n.js
  yarn.lock
Labels: enhancement

#1678 User Detail Drawer Fixes
  client/coral-admin/src/components/UserDetail.js
Labels: enhancement

#1686 Add translations in some missing pages and fix others
  client/coral-admin/src/components/AdminLogin.js
  client/coral-admin/src/components/ForgotPassword.js
  client/coral-admin/src/components/Header.js
  client/coral-admin/src/components/Login.js
  client/coral-admin/src/components/SignIn.js
  client/coral-admin/src/routes/Configure/components/EmbedLink.js
  client/coral-admin/src/routes/Moderation/components/StorySearch.js
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/pt_BR.yml
Labels: in review

#1692 Use neutral icon for aggregated reactions count
  client/coral-embed-stream/src/tabs/profile/components/Comment.js
Labels: in review

#1699 Delete package-lock.json
  docs/package-lock.json
Labels: bug

#1702 Plugin Fixes
  bin/cli-plugins
Labels: bug

#1705 Email Confirm Redirect URI
  graph/connectors.js
  graph/context.js
  plugins/talk-plugin-local-auth/server/mutators.js
  routes/api/v1/users.js
  services/utils.js
  test/server/graph/context.js
Labels: bug

#1715 Search - Display Name
  graph/loaders/users.js
  models/schema/user.js
Labels: enhancement
