Repository coralproject/talk, pull requests merged in 2018-04, with the labels that each got.

#1481 Scraper improvements
  config.js
  docs/source/02-02-advanced-configuration.md
  jobs/scraper/index.js
  jobs/scraper/rules/modified.js
  jobs/scraper/rules/section.js
  package.json
  yarn.lock
Labels: feature

#1502 Webpack and client plugins
  webpack.config.js
Labels: bug

#1503 IfSlotIsNotEmpty Bug
  client/coral-framework/components/IfSlotIsNotEmpty.js
Labels: bug

#1510 Asset Scraping CLI Fix
  bin/cli-assets
Labels: bug

#1513 Logging Improvements
  app.js
  middleware/logging.js
  middleware/trace.js
  package.json
  routes/index.js
  services/logging.js
  services/mongoose.js
  services/redis.js
  yarn.lock
Labels: dev support, enhancement

#1516 Removed unused coral-docs
  client/coral-docs/src/index.js
  client/coral-docs/src/services/fetcher.js
  jest.config.js
Labels: enhancement

#1521 Permission Updates
  graph/resolvers/comment.js
  graph/typeDefs.graphql
  perms/constants/query.js
  perms/reducers/query.js
Labels: bug

#1512 Disable autocomplete on username signup field
  client/coral-ui/components/TextField.js
  plugins/talk-plugin-auth/client/login/components/SignUp.js
Labels: bug

#1518 Ignored User Reply Notifications
  graph/resolvers/user.js
  plugins/talk-plugin-notifications-category-reply/index.js
Labels: bug

#1525 Storage Fixes
  client/coral-admin/src/actions/moderation.js
  client/coral-admin/src/index.js
  client/coral-framework/actions/auth.js
  client/coral-framework/services/i18n.js
  client/coral-framework/services/storage.js
  package.json
Labels: bug

#1522 Serverside Jest Support
  .circleci/config.yml
  .eslintrc.json
  bin/cli
  bin/cli-db
  client/jest.config.js
  jest.config.js
  models/action.js
  models/asset.js
  models/comment.js
  models/migration.js
  models/schema/action.js
  models/schema/asset.js
  models/schema/comment.js
  models/schema/index.js
  models/schema/migration.js
  models/schema/setting.js
  models/schema/user.js
  models/setting.js
  models/user.js
  package.json
  plugin-api/beta/server/getReactionConfig.js
  plugin-api/beta/server/getReactionConfig.spec.js
  plugins/talk-plugin-akismet/index.js
  plugins/talk-plugin-akismet/server/config.js
  plugins/talk-plugin-akismet/server/errors.js
  plugins/talk-plugin-akismet/server/hooks.js
  plugins/talk-plugin-akismet/server/resolvers.js
  plugins/talk-plugin-akismet/server/resolvers.spec.js
  plugins/talk-plugin-akismet/server/typeDefs.graphql
  plugins/talk-plugin-akismet/server/typeDefs.js
  plugins/talk-plugin-toxic-comments/server/__mocks__/perspective.js
  plugins/talk-plugin-toxic-comments/server/hooks.js
  plugins/talk-plugin-toxic-comments/server/hooks.spec.js
  services/logging.js
  services/mongoose.js
  test/setupJest.js
  yarn.lock
Labels: dev support, enhancement

#1507 Bug: User Comment History - After loading more comments, rejecting/accepting a comment reloads the user history
  client/coral-admin/src/components/UserDetail.js
  client/coral-admin/src/containers/UserDetail.js
  client/coral-framework/graphql/mutations.js
Labels: bug

#1504 Account History to User History
  client/coral-admin/src/components/UserDetail.js
  client/coral-admin/src/components/UserHistory.css
  client/coral-admin/src/components/UserHistory.js
  locales/ar.yml
  locales/da.yml
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/nl_NL.yml
  locales/pt_BR.yml
  locales/zh_CN.yml
  locales/zh_TW.yml
  package-lock.json
  test/e2e/page_objects/admin.js
  test/e2e/specs/06_suspendUser.js
Labels: feature

#1531 Adds Author Index for Comments
  models/schema/comment.js
Labels: enhancement

#1496 Organization Email Contact
  client/coral-admin/src/AppRouter.js
  client/coral-admin/src/reducers/install.js
  client/coral-admin/src/routes/Configure/components/Configure.js
  client/coral-admin/src/routes/Configure/components/OrganizationSettings.css
  client/coral-admin/src/routes/Configure/components/OrganizationSettings.js
  client/coral-admin/src/routes/Configure/containers/Configure.js
  client/coral-admin/src/routes/Configure/containers/OrganizationSettings.js
  client/coral-admin/src/routes/Install/components/Install.js
  client/coral-admin/src/routes/Install/components/Steps/OrganizationDetails.js
  client/coral-admin/src/routes/Install/containers/Install.js
  client/coral-framework/components/ConfigureCard.js
  client/coral-framework/helpers/error.js
  client/coral-framework/helpers/validate.js
  client/coral-ui/components/Icon.css
  docs/source/api/slots.md
  graph/typeDefs.graphql
  locales/ar.yml
  locales/da.yml
  locales/de.yml
  locales/en.yml
  locales/es.yml
  locales/fr.yml
  locales/pt_BR.yml
  models/schema/setting.js
  package.json
  services/logging.js
  test/e2e/globals.js
  test/e2e/page_objects/install.js
  test/e2e/specs/01_install.js
Labels: feature

#1493 [GDPR] Download My Comments
  .gitignore
  docs/source/_data/plugins.yml
  docs/source/plugin/talk-plugin-profile-data.md
  graph/connectors.js
  graph/context.js
  graph/mutators/user.js
  graph/resolvers/comment.js
  graph/typeDefs.graphql
  locales/en.yml
  plugins.default.json
  plugins/talk-plugin-profile-data/README.md
  plugins/talk-plugin-profile-data/client/.eslintrc.json
  plugins/talk-plugin-profile-data/client/components/DownloadCommentHistory.css
  plugins/talk-plugin-profile-data/client/components/DownloadCommentHistory.js
  plugins/talk-plugin-profile-data/client/containers/DownloadCommentHistory.js
  plugins/talk-plugin-profile-data/client/graphql.js
  plugins/talk-plugin-profile-data/client/index.js
  plugins/talk-plugin-profile-data/client/mutations.js
  plugins/talk-plugin-profile-data/client/translations.yml
  plugins/talk-plugin-profile-data/index.js
  plugins/talk-plugin-profile-data/package.json
  plugins/talk-plugin-profile-data/server/connect.js
  plugins/talk-plugin-profile-data/server/constants.js
  plugins/talk-plugin-profile-data/server/emails/download.html.ejs
  plugins/talk-plugin-profile-data/server/emails/download.txt.ejs
  plugins/talk-plugin-profile-data/server/errors.js
  plugins/talk-plugin-profile-data/server/mutators.js
  plugins/talk-plugin-profile-data/server/resolvers.js
  plugins/talk-plugin-profile-data/server/router.js
  plugins/talk-plugin-profile-data/server/typeDefs.graphql
  plugins/talk-plugin-profile-data/server/typeDefs.js
  plugins/talk-plugin-profile-data/server/views/download.ejs
  plugins/talk-plugin-profile-data/translations.yml
  public/css/admin.css
  routes/account/index.js
  routes/admin/index.js
  routes/api/v1/account.js
  routes/api/v1/graph.js
  routes/dev/assets.js
  routes/dev/index.js
  routes/index.js
  services/mailer/templates/email-confirm.html.ejs
  services/mailer/templates/email-confirm.txt.ejs
  services/mailer/templates/password-reset.html.ejs
  services/mailer/templates/password-reset.txt.ejs
  services/users.js
  test/e2e/page_objects/embedStream.js
  views/account/email/confirm.ejs
  views/account/password/reset.ejs
  views/api/graphiql.ejs
  views/dev/article.ejs
  views/dev/articles.ejs
  views/embed/stream.ejs
  views/partials/account.ejs
  views/partials/head.ejs
  yarn.lock
Labels: feature

#1532 [GDPR] Password Change
  client/coral-admin/src/routes/Configure/components/OrganizationSettings.js
  client/coral-framework/graphql/fragments.js
  client/coral-framework/graphql/mutations.js
  graph/mutators/user.js
  graph/resolvers/root_mutation.js
  graph/typeDefs.graphql
  locales/en.yml
  perms/constants/mutation.js
  perms/reducers/mutation.js
  plugin-api/beta/client/hocs/index.js
  plugins/talk-plugin-auth/client/index.js
  plugins/talk-plugin-auth/client/profile-settings/components/ChangePassword.css
  plugins/talk-plugin-auth/client/profile-settings/components/ChangePassword.js
  plugins/talk-plugin-auth/client/profile-settings/components/ErrorMessage.css
  plugins/talk-plugin-auth/client/profile-settings/components/ErrorMessage.js
  plugins/talk-plugin-auth/client/profile-settings/components/Form.css
  plugins/talk-plugin-auth/client/profile-settings/components/Form.js
  plugins/talk-plugin-auth/client/profile-settings/components/InputField.css
  plugins/talk-plugin-auth/client/profile-settings/components/InputField.js
  plugins/talk-plugin-auth/client/profile-settings/containers/ChangePassword.js
  plugins/talk-plugin-auth/client/translations.yml
  plugins/talk-plugin-notifications/server/views/unsubscribe-notifications.ejs
  routes/api/v1/account.js
  services/users.js
  views/admin.ejs
  views/embed/stream.ejs
  views/login.ejs
Labels: enhancement, feature

#1542 Use email vs e-mail
  locales/en.yml
  plugins/talk-plugin-auth/client/translations.yml
Labels: enhancement

#1541 Small docs fix
  docs/source/03-03-product-guide-moderator-features.md
Labels: docs

#1545 Decrease font-size and padding in Report comment popup
  client/coral-embed-stream/style/default.css
  client/coral-ui/components/PopupMenu.css
Labels: in review

#1543 Remove refs to talk-plugin-profile-settings
  .gitignore
  docs/source/api/slots.md
  docs/source/integrating/configuring-comment-stream.md
  docs/source/integrating/notifications.md
Labels: docs
