Repository coralproject/talk, pull requests merged in 2019-09, with the labels that each got.

#2519 [CORL-588] Download and token fixes
  src/core/client/account/routes/download/Download/DownloadForm.tsx
  src/core/client/account/routes/download/Download/DownloadRoute.tsx
  src/core/server/app/handlers/api/account/download.ts
  src/core/server/app/handlers/api/index.ts
  src/core/server/app/handlers/api/user/download.ts
  src/core/server/app/handlers/api/user/index.ts
  src/core/server/app/middleware/passport/index.ts
  src/core/server/app/router/api/account.ts
  src/core/server/app/router/api/index.ts
  src/core/server/app/router/api/user.ts
  src/core/server/services/jwt/index.ts
  src/core/server/services/users/download/download.ts
  src/core/server/services/users/download/index.ts
  src/core/server/services/users/download/token.ts
  src/core/server/services/users/index.ts
Labels: bug

#2518 [CORL-577] Moderation Counts Bug
  src/core/server/models/story/counts/shared.ts
Labels: bug

#2551 [CORL-602] Heroku Install Fix
  README.md
Labels: bug

#2552 [CORL-602] Heroku Install Documentation Fix
  docs/source/version-5-installation.md
Labels: bug

#2569 [CORL-621] Auth Fixes
  src/core/client/admin/routes/Configure/sections/Auth/OIDCConfig.tsx
  src/core/client/admin/routes/Configure/sections/Auth/OIDCConfigContainer.tsx
  src/core/client/auth/App/App.tsx
  src/core/client/auth/App/__snapshots__/App.spec.tsx.snap
  src/core/client/auth/dom/resizePopup.ts
  src/core/client/auth/hooks/useResizePopup.ts
  src/core/client/auth/index.tsx
  src/core/client/auth/views/AddEmailAddress/AddEmailAddress.tsx
  src/core/client/auth/views/AddEmailAddress/SetEmailMutation.ts
  src/core/client/auth/views/CreatePassword/CreatePassword.tsx
  src/core/client/auth/views/CreatePassword/SetPasswordMutation.ts
  src/core/client/auth/views/CreateUsername/CreateUsername.tsx
  src/core/client/auth/views/CreateUsername/SetUsernameMutation.ts
  src/core/client/auth/views/ForgotPassword/CheckEmail.tsx
  src/core/client/auth/views/ForgotPassword/ForgotPasswordForm.tsx
  src/core/client/auth/views/SignIn/SignIn.tsx
  src/core/client/auth/views/SignIn/SignInContainer.tsx
  src/core/client/auth/views/SignIn/SignInMutation.ts
  src/core/client/auth/views/SignIn/SignInWithEmailContainer.tsx
  src/core/client/auth/views/SignIn/__snapshots__/SignIn.spec.tsx.snap
  src/core/client/auth/views/SignUp/SignUp.tsx
  src/core/client/auth/views/SignUp/SignUpContainer.tsx
  src/core/client/stream/common/UserBox/UserBoxContainer.spec.tsx
  src/core/client/stream/common/UserBox/UserBoxContainer.tsx
  src/core/client/stream/common/UserBox/__snapshots__/UserBoxContainer.spec.tsx.snap
  src/core/client/ui/components/Popup/Popup.ts
  src/core/server/app/middleware/passport/strategies/oidc/index.ts
  src/core/server/graph/tenant/schema/schema.graphql
Labels: bug

#2583 [CORl-640] User Registration Race
  src/core/server/app/handlers/api/auth/local/signup.ts
  src/core/server/app/handlers/api/install.ts
  src/core/server/app/middleware/passport/strategies/facebook.ts
  src/core/server/app/middleware/passport/strategies/google.ts
  src/core/server/app/middleware/passport/strategies/oidc/index.ts
  src/core/server/app/middleware/passport/strategies/verifiers/sso.ts
  src/core/server/models/user/user.ts
  src/core/server/queue/Task.ts
  src/core/server/services/users/auth/invite.ts
  src/core/server/services/users/index.ts
Labels: bug

#2587 Avoid compute metrics with 404 status code
  src/core/server/app/middleware/metrics.ts
Labels: bug

#2592 [CORL-626] Update MongoDB Version
  docs/source/version-5-development.md
  docs/source/version-5-installation.md
Labels: docs

#2593 [bugfix] Fixed README
  README.md
Labels: docs

#2596 [CORL-647] Comment Action Fix
  src/core/server/models/action/comment.ts
Labels: bug

#2584 v4 - Adding live updates for accepted comments
  graph/subscriptions/setupFunctions.js
  perms/constants/subscription.js
  perms/reducers/subscription.js
Labels: feature idea, v4
