Repository coralproject/talk, pull requests merged in 2019-05, with the labels that each got.

#2279 apply custom CSS to admin panel
  client/coral-admin/src/routes/Configure/components/TechSettings.js
  client/coral-admin/src/routes/Configure/containers/TechSettings.js
  graph/typeDefs.graphql
  locales/en.yml
  middleware/staticTemplate.js
  models/schema/setting.js
  test/server/graph/queries/settings.js
  views/admin.njk
  views/partials/custom-admin-css.njk
Labels: in review

#2299 Show/hide a comment's edit history from Moderation and User Detail.
  client/coral-admin/src/components/UserDetailComment.css
  client/coral-admin/src/components/UserDetailComment.js
  client/coral-admin/src/containers/UserDetailComment.js
  client/coral-admin/src/routes/Moderation/components/Comment.css
  client/coral-admin/src/routes/Moderation/components/Comment.js
  client/coral-admin/src/routes/Moderation/containers/Comment.js
  locales/en.yml
  locales/es.yml
Labels: in review

#2324 [CORL-373] Experimental AMP Support
  client/coral-embed/src/Bridge.js
  client/coral-embed/src/index.js
  middleware/staticTemplate.js
  routes/dev/amp.js
  routes/dev/index.js
  routes/embed/index.js
  views/dev/amp-button.njk
  views/dev/amp.njk
  views/embed/amp.njk
Labels: needs documentation

#2317 CORL-380 | DOCS | Updates pre-launch checklist, asset scraping
  docs/source/01-05-pre-launch-checklist.md
  docs/source/02-03-cli-tools.md
  docs/source/03-06-product-guide-configuring-talk.md
  docs/source/05-03-when-youve-installed-talk.md
  docs/source/integrating/asset-scraping.md
Labels: docs

#2332 [next] Fix Build Issues
  package-lock.json
  package.json
Labels: bug
