Repository coralproject/talk, pull requests merged in 2019-10, with the labels that each got.

#2614 [CORL-661] Encode Story ID
  src/core/client/admin/helpers/getModerationLink.ts
  src/core/client/admin/routes/Moderate/ModerateSearchBar/ModerateSearchBarContainer.tsx
Labels: bug

#2618 Update getReactionConfig.js
  plugin-api/beta/server/getReactionConfig.js
Labels: hacktoberfest

#2623 [CORL-682] OIDC Email and `setEmail` mutation
  app.json
  src/core/server/app/middleware/passport/strategies/oidc/index.ts
  src/core/server/graph/tenant/schema/schema.graphql
Labels: bug

#2626 [CORL-686] Shortcut Fix
  src/core/client/admin/routes/Moderate/Moderate.tsx
Labels: bug

#2630 Add CHANGE_STORY_STATUS permission to Moderators
  src/core/client/admin/permissions.tsx
Labels: bug

#2631 Remove canChangeStatus condition
  src/core/client/admin/routes/Stories/StoryStatus/StoryStatusChangeContainer.tsx
Labels: in review

#2640 [CORL-692] SSO JWT Fix
  src/core/server/app/middleware/passport/strategies/verifiers/sso.spec.ts
  src/core/server/app/middleware/passport/strategies/verifiers/sso.ts
Labels: bug

#2652 [CORL-721] SSO Logout Fix
  src/core/client/auth/local/__snapshots__/initLocalState.spec.ts.snap
  src/core/client/framework/lib/relay/localState.ts
Labels: bug

#2657 [CORL-728] Comment count translation fix
  src/locales/en-US/stream.ftl
Labels: bug

#2655 [CORL-726] Repeat Comment Fix
  src/core/server/services/comments/comments.ts
  src/core/server/services/comments/pipeline/phases/commentLength.ts
  src/core/server/services/comments/pipeline/phases/repeatPost.ts
  src/core/server/services/comments/pipeline/phases/spam.ts
  src/core/server/services/comments/pipeline/phases/toxic.ts
  src/core/server/services/comments/pipeline/pipeline.ts
Labels: bug

#2660 [CORL-689] Link Detection
  client/coral-admin/src/services/linkify.js
  services/moderation/phases/links.js
Labels: bug

#2648 [CORL-646] Docs update
  docs/source/version-5-configuration.md
  docs/source/version-5-counts.md
Labels: docs

#2649 [CORL-646] Simplify README
  README.md
Labels: docs

#2665 Deploy Script Fix
  scripts/docker.sh
Labels: bug

#2666 [CORL-733] Invite Fix
  src/core/client/admin/local/initLocalState.ts
Labels: bug

#2662 [CORL-693] Redirection Loop
  src/core/client/auth/views/SignIn/SignIn.tsx
  src/core/client/auth/views/SignIn/SignInContainer.tsx
  src/core/client/auth/views/SignIn/__snapshots__/SignIn.spec.tsx.snap
  src/core/client/auth/views/SignUp/SignUp.tsx
  src/core/client/auth/views/SignUp/__snapshots__/SignUp.spec.tsx.snap
Labels: bug

#2674 Directive Resolver Bug
  package-lock.json
  package.json
  src/core/server/graph/common/directives/constraint.ts
Labels: bug
