Repository coralproject/talk, pull requests merged in 2020-01, with the labels that each got.

#2777 [CORL-839] Passport Upgrades
  package-lock.json
  package.json
  src/core/server/app/middleware/error.ts
  src/core/server/app/middleware/passport/index.ts
  src/core/server/app/middleware/passport/strategies/oidc/index.ts
  src/core/server/app/url.ts
  src/core/server/models/comment/comment.ts
  src/core/server/models/story/counts/shared.ts
  src/core/server/models/tenant/tenant.ts
  src/core/server/services/notifications/categories/featured.ts
  src/core/server/services/notifications/categories/moderation.ts
  src/core/server/services/notifications/categories/reply.ts
  src/core/server/services/notifications/categories/staffReply.ts
  src/core/server/services/slack/publisher.ts
  src/core/server/services/users/delete.ts
Labels: bug

#2744 [CORL-688] Add user comment count tracking
  src/core/server/graph/tenant/mutators/Actions.ts
  src/core/server/graph/tenant/mutators/Comments.ts
  src/core/server/models/action/moderation/comment.ts
  src/core/server/models/comment/comment.ts
  src/core/server/models/story/counts/index.ts
  src/core/server/models/story/counts/shared.ts
  src/core/server/models/user/user.ts
  src/core/server/services/comments/comments.ts
  src/core/server/services/comments/moderation/index.ts
  src/core/server/services/comments/moderation/moderate.ts
  src/core/server/services/comments/moderation/moderation.spec.ts
  src/core/server/services/comments/moderation/moderation.ts
  src/core/server/services/migrate/migrations/1575649180_user_comment_counts.ts
  src/core/server/stacks/approveComment.ts
  src/core/server/stacks/createComment.ts
  src/core/server/stacks/editComment.ts
  src/core/server/stacks/helpers/index.ts
  src/core/server/stacks/helpers/publishChanges.ts
  src/core/server/stacks/helpers/updateAllCounts.ts
  src/core/server/stacks/index.ts
  src/core/server/stacks/rejectComment.ts
Labels: don't merge

#2776 CORL-753 | DOCs Updates
  docs/_config.yml
  docs/source/06-01-migrating-5.md
  docs/source/07-01-faq.md
  docs/source/07-02-troubleshooting-tips.md
  docs/source/contact.md
  docs/source/integrating/version-5-auth.md
  docs/source/integrating/version-5-css.md
  docs/source/version-5-administration.md
  docs/source/version-5-cli.md
  docs/source/version-5-configuration.md
  docs/source/version-5-development.md
  docs/source/version-5-integrating.md
  docs/source/version-5-notifications.md
  docs/source/version-5-slack.md
  docs/source/version-5-sso.md
  docs/themes/coral/layout/partial/sidebar.swig
Labels: docs

#2784 Heroku Build Fix
  Dockerfile
  package-lock.json
  package.json
Labels: bug, don't merge

#2786 I18n ro translation
  src/core/client/admin/test/configure/__snapshots__/general.spec.tsx.snap
  src/core/common/helpers/i18n/locales.ts
  src/locales/ro/common.ftl
  src/locales/ro/framework.ftl
  src/locales/ro/stream.ftl
Labels: in review

#2785 Banned Tag Fix
  src/core/client/admin/components/ModerateCard/CommentAuthorContainer.tsx
  src/core/client/admin/components/ModerateCard/ModerateCard.tsx
  src/core/client/admin/components/ModerateCard/__snapshots__/ModerateCard.spec.tsx.snap
Labels: bug

#2789 5.4.0 Release Bug Fixes
  .vscode/settings.json
  src/core/client/admin/components/UserHistoryDrawer/RecentHistory.tsx
  src/core/client/admin/routes/Configure/sections/Advanced/CustomCSSConfig.tsx
  src/core/client/admin/routes/Configure/sections/General/ClosingCommentStreamsConfig.tsx
  src/core/client/admin/routes/Configure/sections/General/CommentEditingConfig.tsx
  src/core/client/admin/routes/Configure/sections/Moderation/NewCommentersConfig.tsx
  src/core/client/admin/routes/Configure/sections/Moderation/RecentCommentHistoryConfig.tsx
  src/core/client/admin/test/configure/__snapshots__/advanced.spec.tsx.snap
  src/core/client/admin/test/configure/__snapshots__/moderation.spec.tsx.snap
  src/core/client/admin/test/fixtures.ts
  src/core/client/framework/components/DurationField.spec.tsx
  src/core/client/framework/components/DurationField.tsx
  src/core/client/framework/lib/network/createNetwork.ts
  src/core/client/stream/tabs/Comments/Stream/DeleteAccount/StreamDeletionRequestCalloutContainer.tsx
  src/core/client/stream/tabs/Profile/Settings/ChangeUsername/ChangeUsernameContainer.tsx
  src/core/client/stream/tabs/Profile/Settings/DeleteAccount/Pages/RequestAccountDeletionMutation.tsx
  src/core/client/stream/tabs/Profile/Settings/DownloadCommentsContainer.tsx
  src/core/client/ui/components/v2/DurationField/DurationField.spec.tsx
  src/core/client/ui/components/v2/DurationField/DurationField.tsx
  src/core/client/ui/components/v2/SelectField/SelectField.css
  src/core/client/ui/theme/variables2.ts
  src/core/common/constants.ts
  src/core/common/helpers/i18n/reduceSeconds.ts
  src/core/common/time.ts
  src/core/server/errors/index.ts
  src/core/server/models/story/helpers.ts
  src/core/server/models/tenant/tenant.ts
  src/core/server/queue/Task.ts
  src/core/server/services/comments/comments.ts
  src/core/server/services/jwt/index.ts
  src/core/server/services/users/users.ts
  src/core/server/stacks/editComment.ts
  src/locales/da/admin.ftl
  src/locales/en-US/admin.ftl
  src/locales/fr-FR/admin.ftl
  src/locales/pt-BR/admin.ftl
Labels: bug

#2796 [CORL-867] Health SSL Bypass
  package-lock.json
  package.json
  src/core/server/app/index.ts
  src/core/server/app/router/api/index.ts
Labels: bug

#2797 [CORL-867] Version SSL Bypass
  package-lock.json
  package.json
  src/core/server/app/index.ts
  src/core/server/app/router/api/index.ts
Labels: bug

#2802 Migration Name Format
  src/core/server/services/migrate/migrations/1575649180000_user_comment_counts.ts
Labels: bug

#2807 Translations of server locales in french
  src/core/server/locales/fr-FR/common.ftl
  src/core/server/locales/fr-FR/email.ftl
  src/core/server/locales/fr-FR/errors.ftl
Labels: in review

#2816 [CORL-887] commentCounts Migration Fix
  src/core/server/services/migrate/migrations/1580404849316_user_comment_counts.ts
Labels: bug
