Repository coralproject/talk, pull requests merged in 2020-10, with the labels that each got.

#3182 [CORL-1358] bios
  package-lock.json
  src/core/client/admin/components/ModerateCard/MarkersContainer.spec.tsx
  src/core/client/admin/components/ModerateCard/MarkersContainer.tsx
  src/core/client/admin/components/ModerateCard/__snapshots__/MarkersContainer.spec.tsx.snap
  src/core/client/admin/components/UserHistoryDrawer/MemberBioContainer.css
  src/core/client/admin/components/UserHistoryDrawer/MemberBioContainer.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerContainer.tsx
  src/core/client/admin/routes/Configure/sections/General/GeneralConfigContainer.tsx
  src/core/client/admin/routes/Configure/sections/General/MemberBioConfig.tsx
  src/core/client/admin/test/configure/__snapshots__/general.spec.tsx.snap
  src/core/client/admin/test/fixtures.ts
  src/core/client/framework/components/loadables/MarkdownEditor/MarkdownEditor.tsx
  src/core/client/framework/components/loadables/index.ts
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/CreateCommentReplyMutation.ts
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/ReportCommentForm.tsx
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/ReportCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/ReportFlowContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/UserPopover/UserPopoverContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/UserPopover/UserPopoverOverviewContainer.css
  src/core/client/stream/tabs/Comments/Comment/UserPopover/UserPopoverOverviewContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/Username/UsernameWithPopoverContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/CommentContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Stream/AnsweredCommentsTab/AnsweredCommentContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/FeaturedComments/FeaturedCommentContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
  src/core/client/stream/tabs/Profile/Preferences/BioContainer.css
  src/core/client/stream/tabs/Profile/Preferences/BioContainer.tsx
  src/core/client/stream/tabs/Profile/Preferences/PreferencesContainer.tsx
  src/core/client/stream/tabs/Profile/Preferences/UpdateBioMutation.ts
  src/core/client/stream/test/fixtures.ts
  src/core/client/test/helpers/fixture.ts
  src/core/client/ui/components/v3/TextArea/TextArea.css
  src/core/client/ui/components/v3/TextArea/TextArea.tsx
  src/core/client/ui/components/v3/TextArea/index.ts
  src/core/client/ui/components/v3/index.ts
  src/core/common/constants.ts
  src/core/common/errors.ts
  src/core/server/errors/index.ts
  src/core/server/errors/translations.ts
  src/core/server/graph/mutators/Users.ts
  src/core/server/graph/resolvers/Mutation.ts
  src/core/server/graph/resolvers/Settings.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/locales/en-US/errors.ftl
  src/core/server/models/action/__snapshots__/comment.spec.ts.snap
  src/core/server/models/settings/settings.ts
  src/core/server/models/tenant/tenant.ts
  src/core/server/models/user/user.ts
  src/core/server/services/users/users.ts
  src/locales/en-US/admin.ftl
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3206 [CORL-1402] JWT Parsing
  package-lock.json
  package.json
  src/core/client/framework/lib/auth/helpers.ts
  src/types/jwt-decode.d.ts
Labels: bug, 🚀 merge it!

#3208 [CORL-1405] Fix Timeout Values
  src/core/server/queue/Task.ts
Labels: bug, 🚀 merge it!

#3207 [CORL-1403] GraphQL Caching
  package-lock.json
  package.json
  src/core/common/graphql/index.ts
  src/core/common/graphql/setCacheHint.ts
  src/core/server/app/middleware/graphql/apolloServer.ts
  src/core/server/app/middleware/graphql/cache/redis.ts
  src/core/server/config.ts
  src/core/server/graph/directives/auth.ts
  src/core/server/graph/plugins/metrics.ts
  src/core/server/graph/resolvers/Comment.ts
  src/core/server/graph/resolvers/EditInfo.ts
  src/core/server/graph/resolvers/Query.ts
  src/core/server/graph/resolvers/index.ts
  src/core/server/graph/resolvers/util.ts
  src/core/server/graph/schema/schema.graphql
Labels: 🚀 merge it!

#3209 Bump release version 6.3.7
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3211 [CORL-1406] Cache Bug
  package-lock.json
  package.json
  src/core/client/framework/lib/bootstrap/createManaged.tsx
  src/core/client/framework/lib/network/clearCacheMiddleware.ts
  src/core/client/framework/lib/network/createNetwork.ts
  src/core/client/framework/lib/rest.ts
Labels: bug, 🚀 merge it!

#3213 [CORL-1421] Swap `no-cache` with `no-store`
  package-lock.json
  package.json
  src/core/client/framework/lib/network/clearCacheMiddleware.ts
Labels: bug, 🚀 merge it!

#3214 [CORL-1422] Use POST for authenticated requests
  .circleci/config.yml
  package-lock.json
  package.json
  src/core/client/framework/lib/network/persistedQueriesGetMethodMiddleware.ts
Labels: bug, 🚀 merge it!

#3217 [CORL-1424] Resolve CircleCI Build Issues
  .circleci/config.yml
Labels: bug, 🚀 merge it!

#3218 [CORL-1425] Cache Defaults + Config
  src/core/server/app/middleware/graphql/apolloServer.ts
  src/core/server/config.ts
Labels: 🚀 merge it!

#3202 Feat/french loc update
  src/locales/fr-FR/account.ftl
  src/locales/fr-FR/admin.ftl
  src/locales/fr-FR/auth.ftl
  src/locales/fr-FR/common.ftl
  src/locales/fr-FR/framework.ftl
  src/locales/fr-FR/install.ftl
  src/locales/fr-FR/stream.ftl
Labels: 🚀 merge it!

#3013 Feature/russian localization
  package-lock.json
  src/core/client/admin/test/configure/__snapshots__/general.spec.tsx.snap
  src/core/client/stream/tabs/Profile/Preferences/IgnoreUserSettingsContainer.tsx
  src/core/common/helpers/i18n/locales.ts
  src/locales/ru/framework.ftl
  src/locales/ru/stream.ftl
Labels: 🚀 merge it!

#3222 [CORL-1378] ip based spam detection option
  src/core/client/admin/routes/Configure/sections/Moderation/AkismetConfig.tsx
  src/core/client/admin/test/configure/__snapshots__/moderation.spec.tsx.snap
  src/core/client/admin/test/configure/moderation.spec.tsx
  src/core/client/admin/test/fixtures.ts
  src/core/client/test/helpers/fixture.ts
  src/core/server/graph/resolvers/AkismetExternalIntegration.ts
  src/core/server/graph/resolvers/index.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/models/settings/settings.ts
  src/core/server/models/tenant/tenant.ts
  src/core/server/services/comments/pipeline/phases/spam.ts
  src/locales/en-US/admin.ftl
Labels: 🚀 merge it!

#3220 [CORL-1385] Fix translation general-userBoxAuthenticated-signedIn
  src/locales/da/stream.ftl
  src/locales/en-US/stream.ftl
  src/locales/es/stream.ftl
  src/locales/fi-FI/stream.ftl
  src/locales/fr-FR/stream.ftl
  src/locales/nl-NL/stream.ftl
  src/locales/pl/stream.ftl
  src/locales/pt-BR/stream.ftl
  src/locales/ro/stream.ftl
  src/locales/sv/stream.ftl
Labels: 🚀 merge it!

#3212 [CORL-1419] Count Server Caching
  src/core/server/app/index.ts
  src/core/server/app/middleware/cache.ts
  src/core/server/app/middleware/cacheHeaders.ts
  src/core/server/app/router/api/dashboard.ts
  src/core/server/app/router/api/helpers.ts
  src/core/server/app/router/api/remoteMedia.ts
  src/core/server/app/router/api/story.ts
  src/core/server/app/router/client.ts
  src/core/server/config.ts
Labels: 🚀 merge it!

#3226 [CORL-1440] Allow Replies to have no body
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/CreateCommentReplyMutation.ts
Labels: bug, 🚀 merge it!

#3231 [CORL-1455] Auth Popup Bug
  package-lock.json
  package.json
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
Labels: bug, 🚀 merge it!

#3228 [CORL-1431] Tenant Cache Fix
  src/core/server/services/tenant/cache/__snapshots__/json.spec.ts.snap
  src/core/server/services/tenant/cache/cache.ts
  src/core/server/services/tenant/cache/json.spec.ts
  src/core/server/services/tenant/cache/json.ts
Labels: bug, 🚀 merge it!

#3236 [CORL-1431] Improved Object Stringification
  src/core/server/services/tenant/cache/__snapshots__/json.spec.ts.snap
  src/core/server/services/tenant/cache/json.spec.ts
  src/core/server/services/tenant/cache/json.ts
Labels: bug, 🚀 merge it!

#3223 Remove font-magician and fix material icon font
  package-lock.json
  package.json
  src/core/build/postcss.config.js
  src/core/client/ui/shared/icon.css
  src/core/client/ui/theme/typography.css
Labels: bug, 🚀 merge it!

#3234 [CORL-1401, CORL-1157, CORL-1420] Improve accessibility
  src/core/client/admin/routes/Dashboard/sections/ChartColors.ts
  src/core/client/admin/routes/Dashboard/sections/CommentActivity.css
  src/core/client/admin/routes/Dashboard/sections/CommentActivity.tsx
  src/core/client/admin/routes/Dashboard/sections/SignupActivity.tsx
  src/core/client/admin/routes/Dashboard/sections/SignupActivityTick.tsx
  src/core/client/stream/tabs/Comments/ExternalImageInput/ExternalImageInput.tsx
  src/core/client/stream/tabs/Comments/GiphyInput/GiphyInput.tsx
  src/core/client/stream/tabs/Comments/Stream/SortMenu.css
  src/core/client/stream/tabs/Comments/Stream/SortMenu.spec.tsx
  src/core/client/stream/tabs/Comments/Stream/SortMenu.tsx
  src/core/client/stream/tabs/Comments/Stream/__snapshots__/SortMenu.spec.tsx.snap
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3235 [CORL-1414] Fix mobile styling for RTE pressed buttons
  src/core/client/stream/tabs/Comments/RTE/RTEButton.css
Labels: 🚀 merge it!

#3237 [CORL-1411] Capture replies in slack publish events
  src/core/server/events/listeners/slack/publishEvent.ts
  src/core/server/events/listeners/slack/slack.ts
Labels: 🚀 merge it!

#3238 [CORL-1431] JSON Stringification Fix
  src/core/server/services/tenant/cache/__snapshots__/json.spec.ts.snap
  src/core/server/services/tenant/cache/json.spec.ts
  src/core/server/services/tenant/cache/json.ts
Labels: bug, 🚀 merge it!

#3240 [CORL-1458] PYM Issues
  src/core/client/framework/helpers/onPymMessage.ts
  src/core/client/framework/helpers/potentiallyInjectAxe.ts
  src/core/client/framework/lib/bootstrap/createManaged.tsx
  src/core/client/framework/lib/storage/PymStorage.ts
  src/core/client/stream/common/useHandleIncompleteAccount.ts
Labels: bug, 🚀 merge it!

#3227 polish translation updates
  src/core/server/locales/pl/common.ftl
  src/core/server/locales/pl/email.ftl
  src/core/server/locales/pl/errors.ftl
  src/locales/pl/account.ftl
  src/locales/pl/auth.ftl
  src/locales/pl/common.ftl
  src/locales/pl/framework.ftl
  src/locales/pl/stream.ftl
Labels: 🚀 merge it!

#3242 [CORL-1455] Only show login when enabled
  package-lock.json
  package.json
  src/core/client/admin/components/ModerateCard/ModerateCardContainer.tsx
  src/core/client/admin/routes/Community/InviteUsers/InviteUsersForm.tsx
  src/core/client/admin/routes/Configure/sections/Auth/AuthConfigContainer.tsx
  src/core/client/stream/App/AppContainer.tsx
  src/core/client/stream/common/UserBox/UserBoxContainer.tsx
  src/core/client/stream/common/UserBox/__snapshots__/UserBoxContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReactionButton/ReactionButtonContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/ReportButton.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
Labels: bug, 🚀 merge it!

#3190 Site moderator promotions
  src/core/client/admin/components/UserRole/DemoteUserMutation.ts
  src/core/client/admin/components/UserRole/PromoteUserMutation.ts
  src/core/client/admin/components/UserRole/SiteModeratorActions.css
  src/core/client/admin/components/UserRole/SiteModeratorActions.tsx
  src/core/client/admin/components/UserRole/UserRoleChangeContainer.tsx
  src/core/server/graph/mutators/Users.ts
  src/core/server/graph/resolvers/Mutation.ts
  src/core/server/graph/resolvers/UserModerationScopes.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/models/user/helpers.ts
  src/core/server/models/user/user.ts
  src/core/server/services/users/users.ts
  src/locales/en-US/admin.ftl
Labels: 🚀 merge it!

#3245 [CORL-1408] autofocus media inputs
  package-lock.json
  package.json
  src/core/client/framework/components/__snapshots__/DurationField.spec.tsx.snap
  src/core/client/stream/tabs/Comments/ExternalImageInput/ExternalImageInput.tsx
  src/core/client/stream/tabs/Comments/GiphyInput/GiphyInput.tsx
  src/core/client/ui/components/v2/DurationField/__snapshots__/DurationField.spec.tsx.snap
  src/core/client/ui/components/v2/TextField/TextField.tsx
Labels: bug, 🚀 merge it!

#3251 fix: axios status code ok check
  src/core/server/services/fetch/axios.ts
Labels: bug, 🚀 merge it!

#3225 [CORL-1433] Connected Websocket Metric
  src/core/server/graph/subscriptions/server.ts
  src/core/server/services/metrics/index.ts
Labels: 🚀 merge it!

#3249 [CORL-1435] Avatar CSS
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.css
Labels: 🚀 merge it!

#3250 [CORL-1413] add success message to bio update
  src/core/client/stream/tabs/Profile/Preferences/BioContainer.tsx
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3252 [CORL-1409] prevent long usernames and badges from being cut off on mobile
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/CommentToggle.css
  src/core/client/stream/tabs/Comments/Comment/CommentToggle.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/CommentContainer.spec.tsx.snap
Labels: 🚀 merge it!

#3229 [CORL-1427] Upgrade Sentry
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3246 [CORL-1466] NodeJS Timeouts
  src/core/server/config.ts
  src/core/server/index.ts
Labels: bug, 🚀 merge it!

#3254 Fix typo in Spanish translation
  src/locales/es/stream.ftl
Labels: i18n, 🚀 merge it!

#3241 [CORL-1464] Improve Subscription Memory Usage
  src/core/server/graph/resolvers/Subscription/helpers.ts
Labels: 🚀 merge it!

#3232 [CORL-1407] Improve Subscriptions Performance
  src/core/client/framework/helpers/onPymMessage.ts
  src/core/client/framework/lib/network/clearHTTPCacheMiddleware.ts
  src/core/client/framework/lib/network/createManagedSubscriptionClient.ts
  src/core/client/framework/lib/network/createNetwork.ts
  src/core/client/framework/testHelpers/createTestRenderer.tsx
  src/core/client/stream/constants.ts
  src/core/client/stream/tabs/Comments/PermalinkView/PermalinkView.spec.tsx
  src/core/client/stream/tabs/Comments/PermalinkView/PermalinkView.tsx
  src/core/client/stream/tabs/Comments/PermalinkView/PermalinkViewContainer.css
  src/core/client/stream/tabs/Comments/PermalinkView/PermalinkViewContainer.tsx
  src/core/client/stream/tabs/Comments/PermalinkView/__snapshots__/PermalinkView.spec.tsx.snap
  src/core/client/stream/tabs/Comments/PermalinkView/__snapshots__/PermalinkViewQuery.spec.tsx.snap
  src/core/client/stream/tabs/Comments/ReplyList/CommentReplyCreatedSubscription.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/CommentCreatedSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/CommentEnteredSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/CommentReleasedSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/FeaturedComments/FeaturedCommentContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/SpinnerWhileRendering.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentCreatedSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentReleasedSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabQuery.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabViewNewMutation.tsx
  src/core/client/stream/test/comments/permalink/__snapshots__/permalinkView.spec.tsx.snap
  src/core/client/stream/test/comments/permalink/__snapshots__/permalinkViewCommentNotFound.spec.tsx.snap
  src/core/client/stream/test/comments/permalink/liveDirectReplies.spec.tsx
  src/core/client/stream/test/comments/stream/liveCommentReplies.spec.tsx
  src/core/client/stream/test/comments/stream/liveTopLevelComments.spec.tsx
  src/core/server/events/event.ts
  src/core/server/events/events.ts
  src/core/server/events/listeners/subscription.ts
  src/core/server/events/types.ts
  src/core/server/graph/resolvers/Subscription/commentEntered.ts
  src/core/server/graph/resolvers/Subscription/index.ts
  src/core/server/graph/resolvers/Subscription/types.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/services/events/comments.ts
  src/core/server/stacks/helpers/publishChanges.ts
Labels: 🚀 merge it!

#3253 [CORL-1467] Auth Flow Fixes
  src/core/client/admin/constants.ts
  src/core/client/admin/local/initLocalState.ts
  src/core/client/admin/mutations/SetRedirectPathMutation.spec.ts
  src/core/client/admin/mutations/SetRedirectPathMutation.ts
  src/core/client/admin/routes/Login/AccountCompletionContainer.tsx
  src/core/client/admin/routes/Login/SetAuthViewMutation.ts
  src/core/client/admin/routes/Login/views/LinkAccount/LinkAccountContainer.tsx
  src/core/client/admin/routes/Login/views/SignIn/SignInMutation.ts
  src/core/client/admin/test/auth/accountCompletion.spec.tsx
  src/core/client/admin/test/auth/redirectLoggedIn.spec.tsx
  src/core/client/auth-callback/index.ts
  src/core/client/auth/App/AccountCompletion/AccountCompletionContainer.tsx
  src/core/client/auth/App/AccountCompletion/CompleteAccountMutation.ts
  src/core/client/auth/App/__snapshots__/App.spec.tsx.snap
  src/core/client/auth/local/initLocalState.ts
  src/core/client/auth/test/__snapshots__/signUp.spec.tsx.snap
  src/core/client/auth/test/accountCompletion.spec.tsx
  src/core/client/auth/test/addEmailAddress.spec.tsx
  src/core/client/auth/views/AddEmailAddress/AddEmailAddress.tsx
  src/core/client/auth/views/SignIn/SignInContainer.tsx
  src/core/client/auth/views/SignIn/SignInMutation.ts
  src/core/client/auth/views/SignUp/SignInWithLocalHeader.css
  src/core/client/auth/views/SignUp/SignInWithLocalHeader.tsx
  src/core/client/auth/views/SignUp/SignUp.css
  src/core/client/auth/views/SignUp/SignUp.spec.tsx
  src/core/client/auth/views/SignUp/SignUp.tsx
  src/core/client/auth/views/SignUp/SignUpContainer.tsx
  src/core/client/auth/views/SignUp/__snapshots__/SignUp.spec.tsx.snap
  src/core/client/framework/helpers/redirectOAuth2.ts
  src/core/client/framework/helpers/storageKeys.ts
  src/core/client/framework/lib/auth/auth.ts
  src/core/client/framework/lib/bootstrap/CoralContext.tsx
  src/core/client/framework/lib/bootstrap/createManaged.tsx
  src/core/client/framework/mutations/SetAccessTokenMutation.ts
  src/core/client/install/local/initLocalState.ts
Labels: bug

#3258 [CORL-1417] Fix issue with external images not displaying consistently in admin
  src/core/client/framework/components/Frame.tsx
Labels: bug, 🚀 merge it!

#3261 [CORL-1476] Community Username Breaking
  src/core/client/admin/routes/Community/UserRow.css
Labels: bug, 🚀 merge it!

#3262 [CORL-1480] Duplicate Comment Box Fix
  src/core/client/stream/tabs/Comments/Stream/AddACommentButton.tsx
  src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
Labels: bug, 🚀 merge it!

#3267 [CORL-1485] Revert #3241
  package-lock.json
  package.json
  src/core/server/graph/resolvers/Subscription/helpers.ts
Labels: bug
