Repository coralproject/talk, pull requests merged in 2020-06, with the labels that each got.

#2971 [CORL-1100] External Login Fix
  src/core/server/app/middleware/passport/strategies/oauth2.ts
Labels: bug

#2965 [CORL-1080] Final Form Array Fix
  src/core/client/admin/routes/Configure/sections/Slack/SlackChannel.tsx
  src/core/client/admin/routes/Configure/sections/Slack/SlackConfigContainer.tsx
Labels: bug

#2981 [CORL-1120] Fix SSO Sign Out
  src/core/client/admin/local/__snapshots__/initLocalState.spec.ts.snap
  src/core/client/auth/local/__snapshots__/initLocalState.spec.ts.snap
  src/core/client/framework/lib/relay/localState.ts
  src/core/client/stream/local/__snapshots__/initLocalState.spec.ts.snap
Labels: bug

#2980 [CORL-1119] Scrape Bugfix
  src/core/server/graph/loaders/Stories.ts
Labels: bug

#2994 [CORL-1148] Chrome Local Storage Issues
  package-lock.json
  package.json
  src/core/client/framework/lib/auth/auth.ts
Labels: bug

#2992 [v4] fix: Pin node-gyp to address issue building on Node 8
  .circleci/config.yml
  Dockerfile
Labels: in review

#2998 Docs Update
  docs/source/01-02-configuration.md
  docs/source/02-04-css.md
Labels: docs

#3000 [CORL-1156] Q&A Feature Flag Fix
  package-lock.json
  package.json
  src/core/server/graph/resolvers/StorySettings.ts
  src/core/server/models/story/helpers.ts
  src/core/server/models/story/index.ts
  src/core/server/models/story/story.ts
  src/core/server/services/comments/pipeline/phases/tagExpertAnswers.ts
  src/core/server/services/comments/pipeline/phases/tagUnansweredQuestions.ts
  src/core/server/stacks/createComment.ts
Labels: bug

#3003 Added Kodiak Config
  .kodiak.toml
Labels: 🚀 merge it!

#3007 [CORL-1162] Updated Dashboard Copy
  src/core/client/admin/routes/Dashboard/sections/CommentActivity.tsx
  src/locales/en-US/admin.ftl
Labels: bug, 🚀 merge it!

#3006 [CORL-1161] View Conversation Bug
  src/core/client/stream/tabs/Profile/MyComments/HistoryComment.tsx
  src/core/client/stream/tabs/Profile/MyComments/__snapshots__/HistoryComment.spec.tsx.snap
  src/core/client/stream/test/profile/__snapshots__/myComments.spec.tsx.snap
Labels: bug, 🚀 merge it!

#3005 [CORL-1160] Username not displaying for abusive flags
  src/core/client/admin/components/ModerateCard/FlagDetailsContainer.tsx
Labels: bug, 🚀 merge it!

#3002 Asset Hashing Update
  src/core/build/createWebpackConfig.ts
Labels: 🚀 merge it!

#3008 Fixed Spanish translation typo
  package-lock.json
  package.json
  src/locales/es/stream.ftl
Labels: 🚀 merge it!
