Repository coralproject/talk, pull requests merged in 2020-07, with the labels that each got.

#3011 [CORL-1167] Request Body Size
  package-lock.json
  package.json
  src/core/server/app/middleware/json.ts
  src/core/server/app/router/api/account.ts
  src/core/server/app/router/api/auth.ts
  src/core/server/app/router/api/index.ts
  src/core/server/app/router/api/install.ts
  src/core/server/config.ts
  src/core/server/events/listeners/perspective.ts
  src/core/server/graph/loaders/Stories.ts
  src/core/server/graph/resolvers/LiveConfiguration.ts
  src/core/server/graph/subscriptions/server.ts
  src/core/server/services/comments/pipeline/phases/toxic.ts
  src/core/server/services/comments/pipeline/phases/wordList.ts
  src/core/server/services/stories/scraper/scraper.ts
Labels: bug, 🚀 merge it!

#3014 [CORL-1168] Other Flagging in Admin
  src/core/client/admin/components/ModerateCard/FlagDetails.tsx
  src/core/client/admin/components/ModerateCard/FlagDetailsCategory.css
  src/core/client/admin/components/ModerateCard/FlagDetailsContainer.css
  src/core/client/admin/components/ModerateCard/FlagDetailsContainer.tsx
  src/core/client/admin/components/ModerateCard/FlagDetailsEntry.css
  src/core/client/admin/components/ModerateCard/FlagDetailsEntry.tsx
  src/core/client/admin/components/ModerateCard/Markers.css
  src/core/client/admin/components/ModerateCard/Markers.tsx
  src/core/client/admin/components/ModerateCard/MarkersContainer.spec.tsx
  src/core/client/admin/components/ModerateCard/MarkersContainer.tsx
  src/core/client/admin/components/ModerateCard/ModerateCardDetailsContainer.tsx
  src/core/client/admin/components/ModerateCard/__snapshots__/MarkersContainer.spec.tsx.snap
  src/core/client/admin/test/fixtures.ts
  src/locales/en-US/admin.ftl
Labels: bug, 🚀 merge it!

#3017 [CORL-1174] Set height on iframe embeds in moderate cards
  src/core/client/admin/components/ModerateCard/YouTubeMedia.tsx
  src/core/server/app/handlers/api/oembed/oembed.ts
Labels: 🚀 merge it!

#3018 [CORL-1176] YouTube and Twitter frame-ancestors bug
  src/core/server/app/middleware/csp/tenant.ts
Labels: bug, 🚀 merge it!

#3019 [CORL-1179] Enforce max width/auto scroll on mod card embeds
  src/core/client/admin/components/ModerateCard/GiphyMedia.tsx
  src/core/client/admin/components/ModerateCard/Media.css
Labels: bug, 🚀 merge it!

#3028 [CORL-1184] Replace Dashboard - staff comments icon
  src/core/client/admin/routes/Dashboard/components/TodayDashboardBox.tsx
  src/core/client/admin/routes/Dashboard/sections/Today.tsx
Labels: bug, 🚀 merge it!

#3021 [CORL-1177] Section Selector Bug
  src/core/client/admin/components/PaginatedSelect/PaginatedSelect.css
  src/core/client/admin/routes/Moderate/SiteSelector/SiteSelector.css
Labels: bug, 🚀 merge it!

#3024 use padding-bottom trick to make giphy mp4s responsive
  src/core/client/stream/common/Media/GiphyMedia.css
  src/core/client/stream/common/Media/GiphyMedia.tsx
Labels: bug, 🚀 merge it!

#3023 [CORL-1181] continue polling for twitter iframe height longer
  src/core/client/stream/common/Media/OEmbed.tsx
Labels: bug, 🚀 merge it!

#3026 [CORL-1185] translate error from iframe embeds
  src/core/server/app/handlers/api/oembed/oembed.ts
  src/core/server/app/router/api/index.ts
  src/locales/en-US/common.ftl
Labels: bug, 🚀 merge it!

#3027 [CORL-1192] Reduced Security Mode
  src/core/server/app/middleware/graphql/persistedQueryMiddleware.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/models/tenant/helpers.ts
Labels: 🚀 merge it!

#3020 [CORL-1180] Moderation + Editing Improvements
  src/core/client/admin/mutations/ApproveCommentMutation.ts
  src/core/client/admin/mutations/RejectCommentMutation.ts
  src/core/client/admin/test/moderate/regularQueue.spec.tsx
  src/core/client/admin/test/moderate/rejectedQueue.spec.tsx
  src/core/client/admin/test/moderate/singleComment.spec.tsx
  src/core/server/models/comment/helpers.ts
  src/core/server/services/comments/moderation/moderate.ts
  src/core/server/stacks/approveComment.ts
  src/core/server/stacks/rejectComment.ts
Labels: bug, 🚀 merge it!

#3030 [CORL-1194] correct typo in config
  src/core/client/admin/test/configure/__snapshots__/general.spec.tsx.snap
  src/locales/en-US/admin.ftl
Labels: 🚀 merge it!

#3031 [CORL-1195] Fix bug with displaying site dashboards
  src/core/client/admin/routes/Dashboard/DashboardContainer.tsx
  src/core/client/admin/routes/Dashboard/DashboardRoute.tsx
  src/core/client/admin/routes/Dashboard/SiteDashboardRoute.tsx
Labels: 🚀 merge it!

#3032 [CORL-1124] correct dashboard spacing
  src/core/client/admin/routes/Dashboard/components/TodayDashboardBox.css
Labels: 🚀 merge it!

#3034 [CORL-1191] Show rejected message when replying with banned word
  src/core/client/stream/tabs/Comments/Comment/ReplyEditSubmitStatus.tsx
Labels: 🚀 merge it!

#3035 [CORL-1172] Send staff comments to Slack with all comments enabled
  src/core/server/events/listeners/slack/publishEvent.ts
  src/core/server/events/listeners/slack/slack.ts
Labels: 🚀 merge it!

#3036 [CORL-1199] Show nice error message on network time out
  src/core/client/framework/components/NetworkError.css
  src/core/client/framework/components/NetworkError.tsx
  src/core/client/framework/lib/relay/QueryRenderer.tsx
  src/locales/en-US/common.ftl
Labels: 🚀 merge it!

#3039 pass custom stream css url through to html
  src/core/client/embed/Coral.ts
  src/core/client/embed/StreamEmbed.ts
  src/core/server/app/router/client.ts
  src/core/server/app/views/client.html
Labels: 🚀 merge it!

#3038 remove debug style from comment stream
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.css
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/test/comments/stream/__snapshots__/loadMore.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderCommunityGuidelines.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderMessageBox.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/sortStream.spec.tsx.snap
Labels: 🚀 merge it!

#3042 [CORL-1214] fix logic around repeat posts with or without media embeds:
  src/core/server/services/comments/pipeline/phases/repeatPost.ts
Labels: 🚀 merge it!

#3037 [CORL-1198] Restore ReportCommentEvent
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/CreateCommentDisagreeMutation.ts
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/CreateCommentFlagMutation.ts
Labels: 🚀 merge it!

#3043 [CORL-1202] GraphiQL Bug
  package-lock.json
  package.json
  src/core/server/app/router/index.ts
Labels: bug, 🚀 merge it!

#3045 README.md Update
  .dockerignore
  .gitignore
  README.md
  package.json
Labels: 🚀 merge it!

#3051 [CORL-1219] Media Type Fixes
  src/core/client/admin/test/fixtures.ts
  src/core/client/stream/test/comments/stream/__snapshots__/editComment.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderMessageBox.spec.tsx.snap
  src/core/client/stream/test/fixtures.ts
  src/core/server/graph/resolvers/GiphyMediaConfiguration.ts
  src/core/server/graph/resolvers/MediaConfiguration.ts
  src/core/server/graph/resolvers/Settings.ts
  src/core/server/graph/resolvers/TwitterMediaConfiguration.ts
  src/core/server/graph/resolvers/YouTubeMediaConfiguration.ts
  src/core/server/graph/resolvers/index.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/models/settings/settings.ts
  src/core/server/services/giphy/giphy.ts
Labels: bug

#3046 [CORL-1215] Install Style Tweaks
  .dockerignore
  .gitignore
  README.md
  package-lock.json
  package.json
  src/core/client/install/App/App.css
  src/core/client/install/App/Header.css
  src/core/client/install/App/Header.tsx
  src/core/client/install/App/Wizard.css
  src/core/client/install/App/steps/AddOrganizationStep.tsx
  src/core/client/install/App/steps/FinalStep.tsx
  src/core/client/install/App/steps/PermittedDomainsStep.tsx
  src/core/client/install/App/steps/SelectLanguageStep.tsx
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/CreateCommentDisagreeMutation.ts
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/CreateCommentFlagMutation.ts
  src/core/server/app/router/index.ts
  src/core/server/services/comments/pipeline/phases/repeatPost.ts
Labels: bug

#3054 Site Moderator Fixes
  src/core/client/admin/routes/Moderate/ModerateContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ModerationDropdown/ModerationActionsContainer.tsx
Labels: bug

#3062 [CORL-1229] Scrollbar Bug
  src/core/client/admin/components/PaginatedSelect/PaginatedSelect.css
  src/core/client/admin/routes/Moderate/SectionSelector/SectionSelector.css
  src/core/client/admin/routes/Moderate/SiteSelector/SiteSelector.css
Labels: bug
