Repository coralproject/talk, pull requests merged in 2020-04, with the labels that each got.

#2899 Add tenantDomain to StoryCreatedEventPayload
  WEBHOOKS.md
  src/core/server/events/events.ts
  src/core/server/queue/tasks/webhook/processor.ts
  src/core/server/services/stories/index.ts
Labels: in review

#2919 [CORL-997] Removed crossorigin attribute for custom CSS
  src/core/server/app/views/client.html
  src/core/server/app/views/macros.html
Labels: bug

#2920 [CORL-1001] Wordlist Fixes
  package-lock.json
  package.json
  src/core/client/admin/components/Comment/CommentContent.css
  src/core/client/admin/components/Comment/CommentContent.spec.tsx
  src/core/client/admin/components/Comment/CommentContent.tsx
  src/core/client/admin/components/Comment/__snapshots__/CommentContent.spec.tsx.snap
  src/core/client/admin/components/ModerateCard/ModerateCard.tsx
  src/core/client/admin/components/ModerateCard/ModerateCardContainer.tsx
  src/core/client/admin/components/ModerateCard/__snapshots__/ModerateCard.spec.tsx.snap
  src/core/client/admin/helpers/getPhrasesRegExp.ts
  src/core/client/admin/helpers/index.ts
  src/core/client/admin/helpers/markHTMLNode.ts
  src/core/client/framework/components/loadables/MarkdownEditor/MarkdownEditor.css
  src/core/client/stream/shared/htmlContent.css
  src/core/common/utils/__snapshots__/createWordListRegExp.spec.ts.snap
  src/core/common/utils/createWordListRegExp.spec.ts
  src/core/common/utils/createWordListRegExp.ts
  src/core/common/utils/index.ts
  src/core/server/services/comments/pipeline/wordList.spec.ts
  src/core/server/services/comments/pipeline/wordList.ts
Labels: bug

#2931 [CORL-1002] Queue Improvements
  package.json
  src/core/server/app/handlers/api/graphql.ts
  src/core/server/app/handlers/api/story/count.ts
  src/core/server/app/index.ts
  src/core/server/app/middleware/logging.ts
  src/core/server/app/middleware/metrics.ts
  src/core/server/config.ts
  src/core/server/cron/scheduled/job.ts
  src/core/server/graph/context.ts
  src/core/server/graph/extensions/LoggerExtension.ts
  src/core/server/graph/extensions/MetricsExtension.ts
  src/core/server/graph/resolvers/Query.ts
  src/core/server/graph/resolvers/Queue.ts
  src/core/server/graph/resolvers/Queues.ts
  src/core/server/graph/resolvers/index.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/helpers/createTimer.ts
  src/core/server/helpers/index.ts
  src/core/server/index.ts
  src/core/server/models/comment/comment.ts
  src/core/server/queue/Task.ts
  src/core/server/queue/index.ts
  src/core/server/queue/tasks/Task.ts
  src/core/server/queue/tasks/mailer/index.ts
  src/core/server/queue/tasks/mailer/processor.ts
  src/core/server/queue/tasks/notifier/index.ts
  src/core/server/queue/tasks/notifier/processor.ts
  src/core/server/queue/tasks/rejector.ts
  src/core/server/queue/tasks/scraper.ts
  src/core/server/queue/tasks/webhook/processor.ts
  src/core/server/services/comments/pipeline/wordList.ts
  src/core/server/services/migrate/indexing.ts
  src/core/server/services/migrate/manager.ts
Labels: bug

#2921 [v4] Allow MODERATORS to close asset on stream.
  routes/api/v1/assets.js
  test/server/routes/api/assets/index.js
Labels: in review, v4

#2935 [CORL-1035] Moderated By Bug
  src/core/client/admin/components/ModerateCard/ModerateCardContainer.tsx
  src/core/client/admin/components/ModerateCard/ModeratedByContainer.spec.tsx
  src/core/client/admin/components/ModerateCard/ModeratedByContainer.tsx
  src/core/client/admin/components/ModerateCard/__snapshots__/ModeratedByContainer.spec.tsx.snap
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerAllComments.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerAllCommentsQuery.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerRejectedComments.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerRejectedCommentsQuery.tsx
  src/core/client/admin/local/local.graphql
  src/core/client/admin/mutations/ApproveCommentMutation.ts
  src/core/client/admin/mutations/RejectCommentMutation.ts
  src/core/client/admin/routes/Moderate/Queue/ApprovedQueueRoute.tsx
  src/core/client/admin/routes/Moderate/Queue/Queue.spec.tsx
  src/core/client/admin/routes/Moderate/Queue/Queue.tsx
  src/core/client/admin/routes/Moderate/Queue/QueueRoute.tsx
  src/core/client/admin/routes/Moderate/Queue/RejectedQueueRoute.tsx
  src/core/client/admin/routes/Moderate/SingleModerate/SingleModerateRoute.tsx
  src/core/client/admin/test/moderate/__snapshots__/rejectedQueue.spec.tsx.snap
  src/core/client/admin/test/moderate/regularQueue.spec.tsx
  src/core/client/admin/test/moderate/rejectedQueue.spec.tsx
  src/core/client/admin/test/moderate/singleComment.spec.tsx
Labels: bug

#2937 [CORL-1039] Slack Copy Updates
  src/core/client/admin/routes/Configure/sections/Slack/SlackConfigContainer.tsx
  src/locales/en-US/admin.ftl
  src/locales/pt-BR/admin.ftl
  src/locales/sv/admin.ftl
Labels: bug

#2939 [CORL-1040] Story Update Fix
  .eslintrc.js
  src/core/client/framework/lib/network/persistedQueriesGetMethodMiddleware.ts
  src/core/common/utils/dotize.ts
  src/core/server/app/helpers/entrypoints.ts
  src/core/server/graph/errors.ts
  src/core/server/graph/persisted/loader.ts
  src/core/server/models/action/comment.ts
  src/core/server/models/comment/counts/counts.ts
  src/core/server/models/comment/counts/shared.ts
  src/core/server/services/stories/scraper/scraper.ts
Labels: bug

#2938 [v4] Add translation keys on email subjects of user services
  services/users.js
Labels: v4
