Repository coralproject/talk, pull requests merged in 2020-12, with the labels that each got.

#3310 [CORL-1527] Default to pending queue if global premod is enabled
  src/core/client/admin/routeConfig.tsx
  src/core/client/admin/routes/Moderate/Moderate.tsx
  src/core/client/admin/routes/Moderate/ModerateContainer.tsx
  src/core/client/admin/routes/Moderate/ModerateNavigation/ModerateNavigationContainer.tsx
  src/core/client/admin/routes/Moderate/ModerateNavigation/Navigation.tsx
  src/core/client/admin/routes/Moderate/Queue/ModerationQueue.tsx
  src/core/client/admin/routes/Moderate/Queue/ModerationQueueQuery.tsx
  src/core/client/admin/routes/Moderate/Queue/index.ts
  src/core/client/admin/routes/Moderate/__snapshots__/Moderate.spec.tsx.snap
  src/core/client/admin/test/auth/redirectLoggedOut.spec.tsx
  src/core/client/admin/test/moderate/regularQueue.spec.tsx
  src/core/client/admin/test/moderate/searchBar.spec.tsx
  src/core/client/framework/helpers/index.ts
Labels: 🚀 merge it!

#3317 [CORL-1542] Improved Link Support
  src/core/server/services/comments/pipeline/phases/linkify.ts
Labels: bug, 🚀 merge it!

#3319 [CORL-1537] Duplicate dependancy
  package-lock.json
  package.json
Labels: bug, 🚀 merge it!

#3320 add prometheus buckets for 750ms and 1000ms
  src/core/server/services/metrics/index.ts
Labels: 🚀 merge it!

#3312 [CORL-1533] Ratings and Reviews Enhancements
  src/core/client/admin/components/ModerateCard/ModerateCardContainer.tsx
  src/core/client/stream/local/local.graphql
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabQuery.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/NoComments.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/RatingsFilterMenu.css
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/RatingsFilterMenu.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentForm/RatingInput.tsx
  src/core/client/stream/tabs/Comments/Stream/NoComments/NoComments.tsx
  src/core/client/stream/tabs/Comments/Stream/NoComments/NoQuestionAndAnswers.tsx
  src/core/client/stream/tabs/Comments/Stream/NoComments/NoRatingsAndReviews.tsx
  src/core/client/stream/tabs/Comments/Stream/NoComments/index.ts
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostReviewOrQuestion.tsx
  src/core/client/stream/tabs/Comments/Stream/StoryRating/StoryRating.tsx
  src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabContainer.tsx
  src/core/server/models/story/helpers.ts
  src/core/server/services/comments/pipeline/phases/tagReview.ts
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3287 [CORL-1510] Exposes comment count via REST
  src/core/server/app/handlers/api/story/active.ts
  src/core/server/app/handlers/api/story/count.ts
  src/core/server/app/handlers/api/story/ratings.ts
  src/core/server/app/router/api/story.ts
Labels: 🚀 merge it!

#3315 [CORL-1536] show "copied" feedback in moderate card link buttons
  src/core/client/admin/components/ModerateCard/LinkDetailsContainer.tsx
Labels: 🚀 merge it!

#3318 [CORL-1538] add documentation for integrating with mobile
  docs/_config.yml
  docs/source/02-11-native-mobile.md
Labels: 🚀 merge it!

#3296 russian localization updates and fixes
  src/locales/ru/framework.ftl
  src/locales/ru/stream.ftl
Labels: i18n, 🚀 merge it!

#3316 [CORL-1543] Invite Fix
  src/core/server/models/invite.ts
Labels: bug, 🚀 merge it!

#3306 [CORL-1433] Google Cloud Profiler support
  package-lock.json
  package.json
  src/core/server/config.ts
  src/core/server/index.ts
Labels: 🚀 merge it!

#3323 Directives Fix
  src/core/client/framework/testHelpers/createRelayEnvironment.ts
  src/core/client/framework/testHelpers/createTestRenderer.tsx
  src/core/common/graphql/loadSchema.ts
  src/core/server/graph/schema/index.ts
  src/core/server/index.ts
Labels: bug, 🚀 merge it!

#3321 [CORL-1539] Generate introspection json for v6 API docs
  .circleci/config.yml
  codegen.yml
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3326 [CORL-1523] Show comment reaction usernames in comment history
  src/core/client/stream/tabs/Profile/MyComments/HistoryComment.css
  src/core/client/stream/tabs/Profile/MyComments/HistoryComment.spec.tsx
  src/core/client/stream/tabs/Profile/MyComments/HistoryComment.tsx
  src/core/client/stream/tabs/Profile/MyComments/HistoryCommentContainer.tsx
  src/core/client/stream/tabs/Profile/MyComments/HistoryCommentFooterContainer.css
  src/core/client/stream/tabs/Profile/MyComments/HistoryCommentFooterContainer.tsx
  src/core/client/stream/tabs/Profile/MyComments/__snapshots__/HistoryComment.spec.tsx.snap
  src/core/client/stream/test/fixtures.ts
  src/core/client/stream/test/profile/__snapshots__/myComments.spec.tsx.snap
  src/core/server/graph/resolvers/Comment.ts
  src/core/server/graph/resolvers/Reaction.ts
  src/core/server/graph/resolvers/index.ts
  src/core/server/graph/schema/schema.graphql
Labels: 🚀 merge it!

#3325 [CORL-1529] Add config option to pre-mod comments with suspect words
  src/core/client/admin/routes/Configure/sections/Moderation/PreModerationConfig.tsx
  src/core/client/admin/routes/Configure/sections/WordList/SuspectWordListConfig.tsx
  src/core/client/admin/routes/Configure/sections/WordList/WordListConfigContainer.tsx
  src/core/client/admin/test/configure/__snapshots__/moderation.spec.tsx.snap
  src/core/client/admin/test/fixtures.ts
  src/core/client/test/helpers/fixture.ts
  src/core/server/graph/resolvers/Settings.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/models/settings/settings.ts
  src/core/server/models/tenant/tenant.ts
  src/core/server/services/comments/pipeline/phases/wordList.ts
  src/locales/en-US/admin.ftl
Labels: 🚀 merge it!

#3280 [CORL-378] AMP Support
  package-lock.json
  package.json
  src/core/build/createWebpackConfig.ts
  src/core/build/paths.ts
  src/core/client/embed/Coral.ts
  src/core/client/embed/StreamEmbed.ts
  src/core/client/embed/amp.html
  src/core/client/embed/decorators/withAutoHeight.ts
  src/core/client/embed/decorators/withPymStorage.ts
  src/core/client/embed/index.html
  src/core/client/embed/story.html
  src/core/client/embed/storyAMP.html
  src/core/client/embed/storyButton.html
  src/core/client/embed/utils/coerceStorage.ts
  src/core/client/embed/utils/inMemoryStorage.ts
  src/core/client/embed/utils/index.ts
  src/core/client/stream/index.html
  src/core/server/app/index.ts
  src/core/server/app/middleware/csp.spec.ts
  src/core/server/app/middleware/csp.ts
  src/core/server/app/middleware/csp/index.ts
  src/core/server/app/middleware/csp/tenant.spec.ts
  src/core/server/app/middleware/csp/tenant.ts
  src/core/server/app/router/client.ts
  src/core/server/app/router/index.ts
  src/core/server/app/url.spec.ts
  src/core/server/app/url.ts
  src/core/server/app/views/amp.html
  src/core/server/app/views/macros.html
  src/core/server/config.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/services/sites/url.spec.ts
  src/core/server/services/sites/url.ts
  src/types/@ampproject/toolbox-cache-url.d.ts
Labels: 🚀 merge it!

#3328 [CORL-1549] add go to discussions and go to profile buttons to bottom of stream
  src/core/client/stream/App/SetActiveTabMutation.ts
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsLinks.css
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsLinks.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderMessageBox.spec.tsx.snap
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3329 [CORL-1540] Submit comments to Akismet to improve their evaluation
  src/core/server/graph/mutators/Actions.ts
  src/core/server/graph/mutators/Comments.ts
  src/core/server/services/comments/actions.ts
  src/core/server/services/spam/index.ts
  src/core/server/stacks/approveComment.ts
  src/core/server/stacks/rejectComment.ts
Labels: 🚀 merge it!

#3334 change auth scope for premod settings
  src/core/server/graph/schema/schema.graphql
Labels: 🚀 merge it!

#3335 [CORL-1555] Copy Fixes
  src/core/client/admin/routes/Configure/Link.tsx
  src/core/client/admin/routes/Configure/sections/Moderation/PreModerationConfig.tsx
  src/core/client/admin/routes/Configure/sections/WordList/SuspectWordListConfig.tsx
  src/core/client/admin/test/configure/__snapshots__/moderation.spec.tsx.snap
  src/core/client/ui/components/v3/Link/Link.css
  src/core/client/ui/components/v3/Link/Link.tsx
  src/core/client/ui/components/v3/Link/index.ts
  src/core/client/ui/components/v3/index.ts
  src/locales/en-US/admin.ftl
Labels: 🚀 merge it!

#3339 [CORL-1560] add missing translations
  src/locales/da/stream.ftl
  src/locales/de/stream.ftl
  src/locales/nl-NL/stream.ftl
  src/locales/ro/stream.ftl
Labels: 🚀 merge it!

#3338 [CORL-1557] Closed Stories Fix
  src/core/client/stream/tabs/Comments/Stream/CommentForm/CommentForm.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
Labels: bug, 🚀 merge it!

#3340 [CORL-1563] fix redirect issue from moderate container
  src/core/client/admin/routes/Moderate/ModerateContainer.tsx
Labels: 🚀 merge it!

#3331 [CORL-1524] Add submit comment shortcut: Ctrl+Enter
  package-lock.json
  package.json
  src/core/client/stream/tabs/Comments/RTE/RTE.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentForm/CommentForm.tsx
Labels: 🚀 merge it!

#3341 Bump 6.6.0
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3347 [CORL-1571] WordList Fixes
  src/core/client/admin/helpers/getPhrasesRegExp.ts
  src/core/server/services/tenant/tenant.ts
Labels: bug, 🚀 merge it!

#3348 [CORL-1565] Optionally send Suspect to Pending instead of Premod
  src/core/server/services/comments/pipeline/phases/wordList.ts
Labels: bug, 🚀 merge it!

#3343 [CORL-1567] fix introspeciton.json upload path
  .circleci/config.yml
  package.json
Labels: 🚀 merge it!

#3346 Bump 6.6.1
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3350 [CHORE] Rename master to main and next to develop
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  EXTERNAL_MODERATION_PHASES.md
  scripts/docker.sh
  src/core/client/admin/routes/Configure/sections/ModerationPhases/ConfigureExternalModerationPhase/ExternalModerationPhaseStatus.tsx
  src/core/client/admin/routes/Configure/sections/ModerationPhases/ModerationPhasesConfigContainer.tsx
  src/core/client/admin/routes/Configure/sections/WebhookEndpoints/ConfigureWebhookEndpoint/EndpointStatus.tsx
  src/core/client/admin/routes/Configure/sections/WebhookEndpoints/ConfigureWebhookEndpointForm/EventsSelectField.tsx
  src/core/client/admin/routes/Configure/sections/WebhookEndpoints/WebhookEndpointsConfigContainer.tsx
  src/core/client/admin/test/configure/__snapshots__/webhooks.spec.tsx.snap
Labels: 🚀 merge it!

#3353 [CORL-1586] My Comments Fix
  package-lock.json
  package.json
  src/core/client/stream/tabs/Profile/MyComments/HistoryCommentFooterContainer.tsx
  src/core/client/stream/tabs/Profile/MyComments/MyCommentsContainer.tsx
  src/core/client/stream/test/profile/__snapshots__/myComments.spec.tsx.snap
Labels: bug
