Repository coralproject/talk, pull requests merged in 2020-08, with the labels that each got.

#3064 [CORL-1217] Dangling Reject Fix
  src/core/client/admin/mutations/RejectCommentMutation.ts
Labels: bug

#3066 [CORL-1235] Support Mobile Twitter Links
  src/core/common/helpers/findMediaLinks.spec.ts
  src/core/common/helpers/findMediaLinks.ts
Labels: bug

#3056 Docs update- Jul 2020
  docs/source/01-03-administration.md
  docs/source/02-01-integrating.md
  docs/source/02-02-sso.md
  docs/source/03-01-api.md
Labels: docs

#3067 [CORL-1233] Mobile display fixes
  src/core/client/stream/tabs/Comments/Comment/Comment.css
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.css
  src/core/client/stream/tabs/Comments/Comment/PermalinkButton/PermalinkButton.tsx
  src/core/client/stream/tabs/Comments/Comment/ReactionButton/ReactionButton.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyButton.tsx
  src/core/client/stream/tabs/Comments/Comment/ShowConversationLink.css
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/ReplyButton.spec.tsx.snap
Labels: 🚀 merge it!

#3068 [CORL-1238] Duplicate User Race
  src/core/server/errors/index.ts
  src/core/server/models/user/user.ts
  src/core/server/services/users/users.ts
Labels: bug, 🚀 merge it!

#3071 [CORL-1239] Swap setTimeout for setLongTimeout
  src/core/client/admin/App/DecisionHistory/__snapshots__/DecisionHistoryLoading.spec.tsx.snap
  src/core/client/admin/App/GlobalNotification/useNotification.ts
  src/core/client/admin/routes/AuthCheck/RestrictedContainer.tsx
  src/core/client/stream/local/initLocalState.spec.ts
  src/core/client/stream/mutations/SetCommentIDMutation.spec.ts
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/EditCommentForm/EditCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/ReplyCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/PermalinkView/__snapshots__/PermalinkViewQuery.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Stream/StoryClosedTimeout/StoryClosedTimeoutContainer.tsx
  src/core/client/stream/tabs/Configure/ConfigureQuery.tsx
  src/core/client/stream/tabs/Discussions/DiscussionsQuery.tsx
  src/core/client/stream/tabs/Profile/ProfileQuery.tsx
  src/core/client/ui/components/v2/Delay/Delay.tsx
  src/core/common/helpers/waitFor.ts
  src/core/common/utils/index.ts
  src/core/common/utils/timeout.ts
  src/core/server/services/fetch/abortAfter.ts
  src/core/server/services/fetch/fetch.ts
Labels: bug, 🚀 merge it!

#3059 add react hooks eslint plugin
  .eslintrc.js
  package-lock.json
  package.json
  src/core/client/admin/components/UserHistoryDrawer/UserStatusDetailsContainer.tsx
  src/core/client/admin/routes/Configure/sections/Sites/SiteRoute.tsx
  src/core/client/admin/routes/Dashboard/DashboardContainer.tsx
  src/core/client/stream/common/Media/OEmbed.tsx
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/ReportFlowContainer.tsx
  src/core/client/stream/tabs/Comments/IgnoredTombstoneOrHideContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/SpinnerWhileRendering/SpinnerWhileRendering.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/SpinnerWhileRendering/SpinnerWhileRenderingWrapper.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/SpinnerWhileRendering/index.ts
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/SpinnerWhileRendering.tsx
  src/core/client/stream/tabs/Profile/Settings/ChangeEmail/ChangeEmailContainer.tsx
  src/core/client/ui/components/v3/CallOut/CallOut.css
  src/core/client/ui/components/v3/CallOut/CallOut.tsx
Labels: 🚀 merge it!

#3073 [CORL-794] Create a common date formatter
  src/core/client/framework/hooks/useDateTimeFormat.ts
  src/core/client/ui/hooks/useDateTimeFormat.ts
  src/core/common/date.ts
  src/core/server/services/users/download/download.ts
  src/core/server/services/users/users.ts
Labels: 🚀 merge it!

#3069 [CORL-1227] Fix scroll-able modal position popping
  src/core/client/admin/components/UserRole/SiteModeratorModal.tsx
  src/core/client/ui/components/v2/CheckBox/CheckBox.css
  src/core/client/ui/components/v2/Modal/Modal.css
  src/core/client/ui/components/v2/Modal/Modal.tsx
  src/core/client/ui/components/v2/Modal/__snapshots__/Modal.spec.tsx.snap
Labels: 🚀 merge it!

#3055 [CORL-1226] Comment Count Data Selector
  src/core/client/count/injectJSONPCallback.ts
  src/core/client/count/test/__snapshots__/basic.spec.ts.snap
  src/core/client/count/test/basic.spec.ts
  src/core/server/app/handlers/api/story/count.ts
Labels: 🚀 merge it!

#3077 [CORL-1240] Check existing data before handling subscriptions
  src/core/client/admin/routes/Moderate/Queue/QueueCommentEnteredSubscription.tsx
  src/core/client/admin/routes/Moderate/Queue/QueueCommentLeftSubscription.tsx
  src/core/client/admin/routes/Moderate/SingleModerate/SingleModerateSubscription.tsx
  src/core/client/stream/tabs/Comments/ReplyList/CommentReplyCreatedSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/CommentCreatedSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/CommentReleasedSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentCreatedSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentReleasedSubscription.tsx
Labels: 🚀 merge it!

#3079 [CORL-1246] Add read more opens new tab feature flag
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/CommentContainer.spec.tsx.snap
  src/core/server/graph/schema/schema.graphql
Labels: 🚀 merge it!

#3081 Correctly cleanup timeout
  src/core/client/stream/tabs/Comments/Comment/EditCommentForm/EditCommentFormContainer.tsx
Labels: bug, 🚀 merge it!

#3074 [CORL-1243] Subscription Errors
  src/core/client/framework/lib/network/createManagedSubscriptionClient.ts
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/IndentedComment.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/CommentContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.spec.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.tsx
  src/core/client/stream/tabs/Comments/ReplyList/__snapshots__/ReplyListContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/StoryClosedTimeout/SetStoryClosedMutation.ts
  src/core/client/stream/tabs/Comments/Stream/StoryClosedTimeout/StoryClosedTimeoutContainer.tsx
  src/core/client/stream/test/comments/permalink/permalinkViewPostReply.spec.tsx
  src/core/client/stream/test/comments/stream/charCountReplyComment.spec.tsx
  src/core/client/stream/test/comments/stream/editComment.spec.tsx
  src/core/common/utils/createTimeoutAt.ts
  src/core/common/utils/index.ts
Labels: bug, 🚀 merge it!

#3082 setTimeout Fixes
  src/core/client/auth/hooks/useResizePopup.ts
  src/core/client/framework/components/CopyButton.tsx
  src/core/client/framework/lib/relay/fetch.tsx
  src/core/client/stream/tabs/Comments/Comment/EditCommentForm/EditCommentFormContainer.tsx
Labels: bug, 🚀 merge it!

#3080 [CORL-1242] Ensure SSO Access Tokens are not persisted
  src/core/client/framework/lib/auth/auth.ts
  src/core/client/framework/lib/bootstrap/CoralContext.tsx
  src/core/client/framework/lib/bootstrap/createManaged.tsx
  src/core/client/framework/mutations/SetAccessTokenMutation.ts
  src/core/client/stream/App/listeners/OnPymLogin.spec.tsx
  src/core/client/stream/App/listeners/OnPymLogin.ts
  src/core/client/stream/local/initLocalState.ts
Labels: bug, 🚀 merge it!

#3075 [CORL-1241] Analytics Bugs
  src/core/server/events/listeners/analytics.ts
  src/types/@rudderstack/rudder-sdk-node.d.ts
Labels: bug, 🚀 merge it!

#3085 [CORL-1254] add permit argument to auth directives
  src/core/server/graph/schema/schema.graphql
Labels: 🚀 merge it!

#3078 Use same focus styling for SelectField
  src/core/client/ui/components/v2/SelectField/SelectField.css
Labels: bug, 🚀 merge it!

#3083 [CORL-1251] Restore Autofocus on reply
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/ReplyCommentForm.tsx
Labels: bug, 🚀 merge it!

#3084 [CORL-1244] make spacing between discussions and headers explicit
  src/core/client/stream/tabs/Discussions/MostActiveDiscussionsContainer.css
  src/core/client/stream/tabs/Discussions/MostActiveDiscussionsContainer.tsx
  src/core/client/stream/tabs/Discussions/MyOngoingDiscussionsContainer.css
  src/core/client/stream/tabs/Discussions/MyOngoingDiscussionsContainer.tsx
Labels: 🚀 merge it!

#3086 [CORL-1248] Allow users to auto-show media in stream
  CLIENT_EVENTS.md
  src/core/client/stream/classes.ts
  src/core/client/stream/events.ts
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/MediaSection/MediaSectionContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/FeaturedComments/FeaturedCommentContainer.tsx
  src/core/client/stream/tabs/Profile/MyComments/HistoryCommentContainer.tsx
  src/core/client/stream/tabs/Profile/Preferences/MediaSettingsContainer.css
  src/core/client/stream/tabs/Profile/Preferences/MediaSettingsContainer.tsx
  src/core/client/stream/tabs/Profile/Preferences/PreferencesContainer.tsx
  src/core/client/stream/tabs/Profile/Preferences/UpdateUserMediaSettingsMutation.ts
  src/core/server/graph/mutators/Users.ts
  src/core/server/graph/resolvers/Mutation.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/models/user/user.ts
  src/core/server/services/users/users.ts
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3092 Bump version 6.3.2
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3094 [CORL-1255] Move wordlist check after staff approval check
  src/core/server/services/comments/pipeline/phases/index.ts
Labels: 🚀 merge it!

#3089 [CORL-1188] Add media to comment data downloads
  src/core/server/services/users/download/download.ts
Labels: 🚀 merge it!

#3093 Adding new translation
  src/locales/es/stream.ftl
Labels: 🚀 merge it!

#3096 6.3.2 mobile and responsive UI fixes
  src/core/client/stream/tabs/Comments/Comment/AuthorBadgesContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/Comment.css
  src/core/client/stream/tabs/Comments/Comment/Comment.spec.tsx
  src/core/client/stream/tabs/Comments/Comment/Comment.tsx
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.css
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/CommentToggle.css
  src/core/client/stream/tabs/Comments/Comment/CommentToggle.tsx
  src/core/client/stream/tabs/Comments/Comment/IndentedComment.tsx
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/ReportButton.tsx
  src/core/client/stream/tabs/Comments/Comment/ShowConversationLink.css
  src/core/client/stream/tabs/Comments/Comment/UserTagsContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/Comment.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/CommentContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/IndentedComment.spec.tsx.snap
  src/core/client/stream/test/comments/featured/__snapshots__/renderFeaturedStream.spec.tsx.snap
  src/core/client/stream/test/comments/permalink/__snapshots__/permalinkView.spec.tsx.snap
  src/core/client/stream/test/comments/permalink/__snapshots__/permalinkViewLoadMoreParents.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/editComment.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/loadMore.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postComment.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderCommunityGuidelines.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderReplies.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/reportComment.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/showAllReplies.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/showConversation.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/sortStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/ignoreUser.spec.tsx
  src/core/client/ui/components/v2/MatchMedia/MatchMedia.tsx
  src/core/client/ui/components/v2/Tag/Tag.css
  src/core/client/ui/theme/breakpoints.ts
Labels: bug, 🚀 merge it!

#3095 [CORL-1273] Move Deps
  app.json
  package-lock.json
  package.json
Labels: bug, 🚀 merge it!

#3098 [CORL-1269] Read more conversation fixes
  src/core/client/auth/test/__snapshots__/forgotPassword.spec.tsx.snap
  src/core/client/auth/test/__snapshots__/signIn.spec.tsx.snap
  src/core/client/auth/test/__snapshots__/signUp.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ShowConversationLink.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/ShowConversationLink.spec.tsx.snap
  src/core/client/stream/test/comments/featured/__snapshots__/renderFeaturedStream.spec.tsx.snap
  src/core/client/stream/test/comments/permalink/__snapshots__/permalinkView.spec.tsx.snap
  src/core/client/stream/test/comments/permalink/__snapshots__/permalinkViewCommentNotFound.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/showConversation.spec.tsx.snap
  src/core/client/stream/test/profile/__snapshots__/myComments.spec.tsx.snap
  src/core/client/ui/components/v2/BaseButton/BaseButton.tsx
  src/core/client/ui/components/v2/BaseButton/__snapshots__/BaseButton.spec.tsx.snap
  src/core/server/graph/resolvers/Settings.ts
Labels: bug, 🚀 merge it!

#3097 [CORL-1264] Mark and allow word list timed out comments
  src/core/client/admin/components/ModerateCard/MarkersContainer.spec.tsx
  src/core/client/admin/components/ModerateCard/MarkersContainer.tsx
  src/core/client/admin/components/ModerateCard/__snapshots__/MarkersContainer.spec.tsx.snap
  src/core/server/graph/schema/schema.graphql
  src/core/server/models/comment/revision.ts
  src/core/server/services/comments/pipeline/phases/wordList.ts
  src/locales/en-US/admin.ftl
Labels: 🚀 merge it!

#3102 [CORL-1284] fix missing top border on comment box
  src/core/client/stream/tabs/Comments/Comment/EditCommentForm/EditCommentForm.css
  src/core/client/stream/tabs/Comments/Comment/EditCommentForm/EditCommentForm.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentForm/CommentForm.css
  src/core/client/stream/tabs/Comments/Stream/CommentForm/CommentForm.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentForm.tsx
  src/core/client/stream/test/comments/stream/__snapshots__/editComment.spec.tsx.snap
Labels: 🚀 merge it!

#3103 [CORL-1291] Logging Improvements
  src/core/server/graph/mutators/Settings.ts
  src/core/server/services/tenant/tenant.ts
Labels: 🚀 merge it!

#3100 [CORL-1249] Add "warn" status
  src/core/client/admin/components/UserHistoryDrawer/AccountHistoryAction.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserDrawerAccountHistory.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserStatusDetailsContainer.tsx
  src/core/client/admin/components/UserHistoryDrawer/WarningAction.tsx
  src/core/client/admin/components/UserStatus/RemoveUserWarningMutation.ts
  src/core/client/admin/components/UserStatus/UserStatus.tsx
  src/core/client/admin/components/UserStatus/UserStatusChange.tsx
  src/core/client/admin/components/UserStatus/UserStatusChangeContainer.tsx
  src/core/client/admin/components/UserStatus/UserStatusContainer.tsx
  src/core/client/admin/components/UserStatus/WarnForm.css
  src/core/client/admin/components/UserStatus/WarnForm.tsx
  src/core/client/admin/components/UserStatus/WarnModal.tsx
  src/core/client/admin/components/UserStatus/WarnUserMutation.ts
  src/core/client/admin/test/fixtures.ts
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/RefreshUserFetch.ts
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/Warning/AcknowledgeWarningMutation.ts
  src/core/client/stream/tabs/Comments/Stream/Warning/Warning.css
  src/core/client/stream/tabs/Comments/Stream/Warning/Warning.tsx
  src/core/client/stream/tabs/Comments/Stream/Warning/WarningContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/Warning/index.ts
  src/core/client/stream/tabs/Comments/helpers/index.ts
  src/core/client/stream/tabs/Comments/helpers/shouldTriggerUserRefresh.ts
  src/core/client/stream/test/fixtures.ts
  src/core/client/stream/test/helpers/fixture.ts
  src/core/client/test/helpers/fixture.ts
  src/core/common/errors.ts
  src/core/server/errors/index.ts
  src/core/server/errors/translations.ts
  src/core/server/graph/directives/auth.ts
  src/core/server/graph/mutators/Users.ts
  src/core/server/graph/resolvers/Mutation.ts
  src/core/server/graph/resolvers/UserStatus.ts
  src/core/server/graph/resolvers/WarningStatus.ts
  src/core/server/graph/resolvers/WarningStatusHistory.ts
  src/core/server/graph/resolvers/index.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/locales/en-US/errors.ftl
  src/core/server/models/user/user.ts
  src/core/server/services/users/users.ts
  src/locales/en-US/admin.ftl
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3106 [CORL-1211] Upgrade RTE
  package-lock.json
  package.json
  src/core/client/stream/tabs/Comments/RTE/__snapshots__/RTE.spec.tsx.snap
Labels: 🚀 merge it!

#3108 Translate 2
  src/locales/es/stream.ftl
Labels: 🚀 merge it!

#3110 [CORL-1304] fix radio button alignment in safari and mobile safari
  src/core/client/ui/components/v2/RadioButton/RadioButton.css
Labels: 🚀 merge it!

#3105 [CORL-1285] Support older browser
  package-lock.json
  package.json
  scripts/webpackHotDevClient.js
  src/core/client/framework/helpers/index.ts
  src/core/client/framework/helpers/injectConditionalPolyfills.tsx
  src/core/client/framework/helpers/polyfillCSSVars.tsx
  src/core/client/framework/helpers/polyfillCSSVarsForIE11.tsx
  src/core/client/framework/helpers/polyfillIntlLocale.tsx
  src/core/client/framework/lib/bootstrap/createManaged.tsx
  src/core/client/framework/lib/browserInfo.ts
  src/core/client/framework/lib/relay/lookup.ts
  src/core/client/framework/testHelpers/createTestRenderer.tsx
  src/core/client/stream/tabs/Configure/ConfigureQuery.tsx
  src/core/client/stream/tabs/Discussions/DiscussionsQuery.tsx
  src/core/client/stream/tabs/Profile/ProfileQuery.tsx
  src/types/intl.d.ts
Labels: 🚀 merge it!

#3113 Translate 3
  src/locales/es/stream.ftl
Labels: 🚀 merge it!

#3114 [CORL-1306] Use v3 buttons on CommentForm
  src/core/client/stream/tabs/Comments/Stream/CommentForm/CommentForm.css
  src/core/client/stream/tabs/Comments/Stream/CommentForm/CommentForm.tsx
  src/core/client/stream/test/comments/stream/__snapshots__/editComment.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderMessageBox.spec.tsx.snap
Labels: 🚀 merge it!

#3107 [CORL-1282] Hide user media preferences if all media types are disabled
  src/core/client/stream/tabs/Profile/Preferences/MediaSettingsContainer.tsx
  src/core/client/stream/tabs/Profile/Preferences/PreferencesContainer.tsx
  src/core/client/stream/tabs/Profile/Profile.tsx
  src/core/client/stream/tabs/Profile/ProfileContainer.tsx
Labels: 🚀 merge it!

#3124 Update pt-BR translation
  src/core/server/locales/pt-BR/common.ftl
  src/core/server/locales/pt-BR/errors.ftl
  src/locales/pt-BR/account.ftl
  src/locales/pt-BR/admin.ftl
  src/locales/pt-BR/auth.ftl
  src/locales/pt-BR/common.ftl
  src/locales/pt-BR/stream.ftl
Labels: 🚀 merge it!

#3122 [CORL-1263] Display warning messages in user account history
  package-lock.json
  src/core/client/admin/components/UserHistoryDrawer/UserDrawerAccountHistory.css
  src/core/client/admin/components/UserHistoryDrawer/UserDrawerAccountHistory.tsx
  src/core/server/graph/schema/schema.graphql
Labels: 🚀 merge it!

#3125 CircleCI Resource Class
  .circleci/config.yml
Labels: 🚀 merge it!

#3121 [CORL-1281] Prevent viewNewEdges from being garbage collected
  package-lock.json
  package.json
  src/core/client/admin/routes/Moderate/Queue/QueueRoute.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/CreateCommentReplyMutation.ts
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabContainer.tsx
Labels: 🚀 merge it!

#3126 [CORL-1292] Set better aria labels on the comment action buttons
  src/core/client/admin/routes/Configure/sections/General/ReactionConfig.tsx
  src/core/client/admin/test/configure/__snapshots__/general.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/PermalinkButton/PermalinkButton.tsx
  src/core/client/stream/tabs/Comments/Comment/PermalinkButton/PermalinkButtonContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReactionButton/CreateCommentReactionMutation.ts
  src/core/client/stream/tabs/Comments/Comment/ReactionButton/ReactionButton.tsx
  src/core/client/stream/tabs/Comments/Comment/ReactionButton/ReactionButtonContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReactionButton/RemoveCommentReactionMutation.ts
  src/core/client/stream/tabs/Comments/Comment/ReplyButton.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/CommentContainer.spec.tsx.snap
  src/core/client/stream/test/comments/featured/__snapshots__/renderFeaturedStream.spec.tsx.snap
  src/core/client/stream/test/comments/permalink/__snapshots__/permalinkView.spec.tsx.snap
  src/core/client/stream/test/comments/permalink/__snapshots__/permalinkViewLoadMoreParents.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/editComment.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/loadMore.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postComment.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/reaction.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderCommunityGuidelines.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderReplies.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/reportComment.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/showAllReplies.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/showConversation.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/sortStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/reaction.spec.tsx
  src/locales/en-US/admin.ftl
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3115 [CORL-1281] Speed up comment contents loading by removing wordlist from queries
  src/core/client/admin/components/Comment/CommentContent.tsx
  src/core/client/admin/components/ConversationModal/ConversationModalCommentContainer.tsx
  src/core/client/admin/components/ModerateCard/CommentRevisionContainer.tsx
  src/core/client/admin/components/ModerateCard/ModerateCardDetailsContainer.tsx
Labels: 🚀 merge it!

#3133 [CORL-1320] Add badges back to CommentContainer fragment
  src/core/client/stream/tabs/Comments/Comment/AuthorBadges.tsx
  src/core/client/stream/tabs/Comments/Comment/AuthorBadgesContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/CommentContainer.spec.tsx.snap
Labels: 🚀 merge it!

#3132 [CORL-1317] Warning Messaging Improvements
  src/core/client/framework/constants.ts
  src/core/client/stream/common/WarningError.tsx
  src/core/client/stream/constants.ts
  src/core/client/stream/tabs/Comments/Comment/ReactionButton/CreateCommentReactionMutation.ts
  src/core/client/stream/tabs/Comments/Comment/ReactionButton/ReactionButtonContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReactionButton/RemoveCommentReactionMutation.ts
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/ReplyCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/ReplyCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReportFlow/ReportCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/CommentContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/RefreshViewerFetch.ts
  src/core/client/stream/tabs/Comments/Stream/Announcement/AnnouncementContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/Warning/Warning.tsx
  src/core/client/stream/tabs/Comments/Stream/Warning/WarningContainer.tsx
  src/core/client/stream/tabs/Comments/helpers/index.ts
  src/core/client/stream/tabs/Comments/helpers/shouldTriggerViewerRefresh.ts
  src/core/server/graph/resolvers/Comment.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/locales/en-US/errors.ftl
  src/core/server/locales/pt-BR/errors.ftl
  src/core/server/services/users/users.ts
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3134 [CORL-1316] Adjust flex and text wrapping of external media url's
  src/core/client/stream/tabs/Comments/Comment/MediaConfirmation/MediaPreview.css
  src/core/client/stream/tabs/Comments/Comment/MediaConfirmation/MediaPreview.tsx
Labels: 🚀 merge it!

#3137 [CORL-1319] Set width and height on avatar container
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.css
Labels: 🚀 merge it!

#3131 [CORL-1315] Enhance loading and security for external resources
  src/core/client/admin/components/MediaContainer/ExternalMedia.tsx
  src/core/client/admin/components/MediaContainer/GiphyMedia.tsx
  src/core/client/admin/components/MediaContainer/Media.css
  src/core/client/admin/components/MediaContainer/MediaContainer.tsx
  src/core/client/admin/components/MediaContainer/TwitterMedia.tsx
  src/core/client/admin/components/MediaContainer/YouTubeMedia.tsx
  src/core/client/framework/components/Frame.tsx
  src/core/client/stream/common/Media/ExternalMedia.tsx
  src/core/client/stream/common/Media/GiphyMedia.tsx
  src/core/client/stream/common/Media/IframeEmbed.tsx
  src/core/client/stream/common/Media/OEmbed.css
  src/core/client/stream/common/Media/TwitterMedia.tsx
  src/core/client/stream/common/Media/YouTubeMedia.tsx
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/MediaSection/MediaSectionContainer.tsx
  src/core/client/stream/tabs/Comments/GifSelector/GifSelector.tsx
  src/core/server/app/views/image.html
  src/core/server/app/views/oembed.html
  src/types/pym.d.ts
Labels: 🚀 merge it!

#3138 Bump Version 6.3.3
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3139 [CORL-1323] Media Fixes
  src/core/client/stream/tabs/Comments/Comment/EditCommentForm/EditCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/MediaConfirmation/MediaConfirmation.tsx
  src/core/client/stream/tabs/Comments/Comment/MediaConfirmation/MediaPreview.tsx
  src/core/client/stream/tabs/Comments/ExternalImageInput/ExternalImageInput.tsx
  src/core/client/stream/tabs/Comments/GifSelector/GifPreview.tsx
  src/core/client/stream/tabs/Comments/GifSelector/GifSelector.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentForm/CommentForm.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentForm/MediaField.tsx
  src/core/client/stream/test/comments/stream/__snapshots__/editComment.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderMessageBox.spec.tsx.snap
  src/core/common/errors.ts
  src/core/common/helpers/findMediaLinks.ts
  src/core/server/app/handlers/api/externalMedia.ts
  src/core/server/app/handlers/api/oembed.ts
  src/core/server/app/request/__snapshots__/body.spec.ts.snap
  src/core/server/app/request/body.ts
  src/core/server/app/router/api/index.ts
  src/core/server/errors/index.ts
  src/core/server/errors/translations.ts
  src/core/server/locales/en-US/errors.ftl
Labels: bug, 🚀 merge it!

#3141 [CORL-1325] Media Form Fixes
  src/core/client/stream/tabs/Comments/ExternalImageInput/ExternalImageInput.tsx
  src/core/client/stream/tabs/Comments/GifSelector/index.ts
  src/core/client/stream/tabs/Comments/GiphyInput/GifPreview.css
  src/core/client/stream/tabs/Comments/GiphyInput/GifPreview.tsx
  src/core/client/stream/tabs/Comments/GiphyInput/GifSearchFetch.ts
  src/core/client/stream/tabs/Comments/GiphyInput/GiphyAttribution.css
  src/core/client/stream/tabs/Comments/GiphyInput/GiphyAttribution.tsx
  src/core/client/stream/tabs/Comments/GiphyInput/GiphyInput.css
  src/core/client/stream/tabs/Comments/GiphyInput/GiphyInput.tsx
  src/core/client/stream/tabs/Comments/GiphyInput/giphyAttribution.png
  src/core/client/stream/tabs/Comments/GiphyInput/index.ts
  src/core/client/stream/tabs/Comments/Stream/CommentForm/MediaField.tsx
Labels: bug, 🚀 merge it!

#3143 [CORL-1321] Fix external image input/submit on small mobile screens
  src/core/client/stream/tabs/Comments/ExternalImageInput/ExternalImageInput.tsx
Labels: 🚀 merge it!

#3101 [CORL-1277] Replace fetch for axios on perspective requests
  package-lock.json
  package.json
  src/core/server/services/fetch/axios.ts
  src/core/server/services/fetch/index.ts
  src/core/server/services/perspective/perspective.ts
Labels: 🚀 merge it!

#3146 [CORL-1265] Add sarcasm RTE feature
  config/jest/client.config.js
  src/core/client/stream/shared/htmlContent.css
  src/core/client/stream/tabs/Comments/RTE/RTE.tsx
  src/core/client/stream/tabs/Comments/RTE/RTEContainer.tsx
  src/core/client/stream/tabs/Comments/RTE/Sarcasm.ts
  src/core/client/stream/test/comments/stream/rte.spec.tsx
  src/core/client/stream/test/fixtures.ts
  src/core/common/constants.ts
  src/core/common/helpers/sanitize.ts
  src/core/server/graph/resolvers/Settings.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/models/settings/settings.ts
  src/core/server/services/comments/pipeline/phases/purify.ts
  src/locales/en-US/stream.ftl
  src/types/squire-rte.d.ts
Labels: 🚀 merge it!

#3147 Bump version 6.3.4
  data/redis/dump.rdb
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3148 Bump version 6.3.5
  data/redis/dump.rdb
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3149 [CORL-1296] New Comment Count
  package-lock.json
  package.json
  src/core/client/admin/routes/Dashboard/sections/CommentActivity.tsx
  src/core/client/admin/routes/Dashboard/sections/SignupActivity.tsx
  src/core/client/admin/routes/Dashboard/sections/Today.tsx
  src/core/client/admin/routes/Dashboard/sections/TopStories.tsx
  src/core/client/count/injectJSONPCallback.ts
  src/core/client/embed/story.html
  src/core/client/embed/storyButton.html
  src/core/client/framework/helpers/getPreviousCountStorageKey.ts
  src/core/client/stream/tabs/Comments/GiphyInput/GifSearchFetch.ts
  src/core/client/stream/tabs/Comments/GiphyInput/GiphyInput.tsx
  src/core/client/stream/tabs/Comments/ReplyList/CommentReplyCreatedSubscription.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyList.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.spec.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListViewNewMutation.tsx
  src/core/client/stream/tabs/Comments/ReplyList/__snapshots__/ReplyListContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabViewNewMutation.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentForm/MediaField.tsx
  src/core/client/stream/tabs/Comments/Stream/PreviousCountSpyContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
  src/core/client/stream/tabs/Comments/helpers/incrementStoryCommentCounts.ts
  src/core/common/types/count.ts
  src/core/common/types/dashboard.ts
  src/core/common/types/giphy.ts
  src/core/common/types/index.ts
  src/core/server/app/handlers/api/dashboard/index.ts
  src/core/server/app/handlers/api/story/count.ts
  src/core/server/graph/resolvers/Settings.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/queue/tasks/mailer/processor.ts
  src/core/server/services/giphy/giphy.ts
Labels: 🚀 merge it!

#3150 [CORL-1332] By default load 10 replies before showing expand options
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.tsx
  src/core/client/stream/test/comments/stream/showAllReplies.spec.tsx
Labels: 🚀 merge it!

#3152 [CORL-1336] update left margins for indented comments
  src/core/client/stream/tabs/Comments/Indent.css
Labels: 🚀 merge it!

#3153 [CORL-1345] Disable build cache for production builds
  src/core/build/createWebpackConfig.ts
Labels: bug, 🚀 merge it!

#3151 [CORL-1297] Move Comment Box
  src/core/client/stream/constants.ts
  src/core/client/stream/tabs/Comments/Stream/AddACommentButton.css
  src/core/client/stream/tabs/Comments/Stream/AddACommentButton.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsLinks.css
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsLinks.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentForm.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormFake.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/__snapshots__/PostCommentFormFake.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
  src/core/client/stream/test/comments/featured/__snapshots__/renderFeaturedStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/loadMore.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderCommunityGuidelines.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderMessageBox.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/sortStream.spec.tsx.snap
  src/core/server/graph/resolvers/Settings.ts
  src/core/server/graph/schema/schema.graphql
Labels: 🚀 merge it!
