Repository coralproject/talk, pull requests merged in 2020-11, with the labels that each got.

#3247 [CORL-1443] Update Joi and improve error logging
  package-lock.json
  package.json
  scripts/watcher/types.ts
  scripts/watcher/watch.ts
  src/core/server/app/handlers/api/account/confirm.ts
  src/core/server/app/handlers/api/account/download.ts
  src/core/server/app/handlers/api/account/invite.ts
  src/core/server/app/handlers/api/auth/local/forgot.ts
  src/core/server/app/handlers/api/auth/local/link.ts
  src/core/server/app/handlers/api/auth/local/signup.ts
  src/core/server/app/handlers/api/externalMedia.ts
  src/core/server/app/handlers/api/install.ts
  src/core/server/app/handlers/api/oembed.ts
  src/core/server/app/handlers/api/remoteMedia.ts
  src/core/server/app/handlers/api/story/active.ts
  src/core/server/app/handlers/api/story/count.ts
  src/core/server/app/middleware/passport/index.ts
  src/core/server/app/middleware/passport/strategies/local.ts
  src/core/server/app/middleware/passport/strategies/oidc/index.ts
  src/core/server/app/middleware/passport/strategies/verifiers/jwt.ts
  src/core/server/app/middleware/passport/strategies/verifiers/sso.ts
  src/core/server/app/request/body.spec.ts
  src/core/server/app/request/body.ts
  src/core/server/config.ts
  src/core/server/helpers/validateSchema.ts
  src/core/server/models/action/comment.ts
  src/core/server/queue/tasks/mailer/processor.ts
  src/core/server/services/comments/pipeline/phases/external.ts
  src/core/server/services/giphy/giphy.ts
  src/core/server/services/jwt/index.ts
  src/core/server/services/management/management.ts
  src/core/server/services/notifications/categories/unsubscribe.ts
  src/core/server/services/oembed/oembed.ts
  src/core/server/services/users/auth/confirm.ts
  src/core/server/services/users/auth/invite.ts
  src/core/server/services/users/auth/reset.ts
  src/core/server/services/users/download/token.ts
Labels: 🚀 merge it!

#3256 [CORL-1415] fix mobile display of tombstones
  src/core/client/ui/components/v3/Tombstone/Tombstone.css
Labels: bug, 🚀 merge it!

#3257 [CORL-1418] allow usernames in popovers to line break
  src/core/client/stream/tabs/Comments/Comment/UserPopover/UserPopoverOverviewContainer.css
  src/core/client/stream/tabs/Comments/Comment/UserPopover/UserPopoverOverviewContainer.tsx
Labels: bug, 🚀 merge it!

#3263 [CORL-1459] add padding to error message on signup form
  src/core/client/auth/test/__snapshots__/signIn.spec.tsx.snap
  src/core/client/auth/views/SignIn/SignInWithEmail.tsx
Labels: bug, 🚀 merge it!

#3264 [CORL-1479] ensure gif preview fits in viewport
  src/core/client/stream/tabs/Comments/GiphyInput/GifPreview.css
  src/core/client/stream/tabs/Comments/GiphyInput/GifPreview.tsx
Labels: bug, 🚀 merge it!

#3265 [CORL-1483] add fallback font to open sans font-face declaration
  CSS_VARIABLES.md
  src/core/client/ui/components/v2/SelectField/SelectField.css
  src/core/client/ui/theme/sharedVariables.ts
Labels: bug, 🚀 merge it!

#3266 [CORL-1481] add media container into answered comments
  src/core/client/stream/tabs/Comments/Stream/AnsweredCommentsTab/AnsweredCommentContainer.tsx
Labels: bug, 🚀 merge it!

#3269 [CORL-1487] Storage Fallback
  src/core/client/embed/decorators/withPymStorage.ts
  src/core/client/embed/utils/inMemoryStorage.ts
  src/core/client/embed/utils/index.ts
Labels: bug, 🚀 merge it!

#3259 [CORL-1372] Update design for viewers reading callout
  src/core/client/stream/tabs/Comments/Stream/ViewersWatchingContainer.css
  src/core/client/stream/tabs/Comments/Stream/ViewersWatchingContainer.tsx
  src/locales/en-US/stream.ftl
Labels: bug, 🚀 merge it!

#3260 [CORL-1354] add all comments footer to all sort orders
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsLinks.css
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsLinks.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.css
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/test/comments/stream/__snapshots__/loadMore.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/postLocalReply.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderCommunityGuidelines.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderMessageBox.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/sortStream.spec.tsx.snap
Labels: bug, 🚀 merge it!

#3271 fix comments:suggestscore from perspective API
  src/core/server/services/perspective/perspective.ts
Labels: bug, 🚀 merge it!

#3274 [CORL-1495] Improve Cache Busting
  src/core/build/createWebpackConfig.ts
  src/core/client/embed/Coral.ts
  src/core/client/embed/FrameControl.ts
  src/core/client/embed/PymControl.ts
  src/core/client/embed/PymFrameControl.spec.ts
  src/core/client/embed/PymFrameControl.ts
  src/core/client/embed/StreamEmbed.spec.ts
  src/core/client/embed/StreamEmbed.ts
  src/core/client/embed/__snapshots__/PymFrameControl.spec.ts.snap
  src/core/client/embed/__snapshots__/StreamEmbed.spec.ts.snap
  src/core/client/embed/index.ts
  src/core/client/embed/test/__snapshots__/basic.spec.ts.snap
  src/core/client/embed/test/basic.spec.ts
  src/core/common/utils/stringifyQuery.ts
Labels: bug, 🚀 merge it!

#3268 Add missing pt-br translations
  src/core/server/locales/pt-BR/errors.ftl
  src/locales/pt-BR/admin.ftl
  src/locales/pt-BR/framework.ftl
  src/locales/pt-BR/stream.ftl
Labels: i18n, 🚀 merge it!

#3276 [CORL-1499] Cleanly dipose pym listeners
  src/core/client/framework/helpers/onPymMessage.ts
  src/core/client/framework/helpers/onPymMessageOnce.ts
Labels: bug, 🚀 merge it!

#3275 [CORL-1498] Correctly load resources in css when using Static URI Path
  src/core/build/createWebpackConfig.ts
Labels: bug, 🚀 merge it!

#3277 [CORL-1500] improve popup close detection
  src/core/client/ui/components/v2/Popup/Popup.ts
Labels: bug, 🚀 merge it!

#3279 [CORL-1501] Fixed type with commentEntered event
  src/core/server/graph/resolvers/CommentEnteredPayload.ts
  src/core/server/graph/resolvers/Subscription/commentEntered.ts
  src/core/server/graph/resolvers/index.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/services/events/comments.ts
Labels: bug, 🚀 merge it!

#3278 [CORL-1502] Publish Static Files on Tag
  .circleci/config.yml
  package-lock.json
  package.json
  scripts/docker.sh
Labels: 🚀 merge it!

#3281 [CORL-1496] Moderation Link Improvements
  src/core/client/framework/helpers/getModerationLink.ts
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ModerationDropdown/CaretContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ModerationDropdown/ModerationActionsContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ModerationDropdown/ModerationDropdownContainer.tsx
  src/core/client/stream/test/comments/stream/moderation.spec.tsx
Labels: bug, 🚀 merge it!

#3255 [CORL-1412] Integrate giphy web SDK
  package-lock.json
  package.json
  src/core/client/auth/hooks/useResizePopup.ts
  src/core/client/framework/hooks/index.ts
  src/core/client/framework/hooks/useResizeObserver.ts
  src/core/client/stream/tabs/Comments/Comment/EditCommentForm/EditCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/ReplyCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/ReplyCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/__snapshots__/ReplyCommentFormContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/GiphyInput/GiphyInput.css
  src/core/client/stream/tabs/Comments/GiphyInput/GiphyInput.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentForm/CommentForm.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentForm/MediaField.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/__snapshots__/PostCommentFormContainer.spec.tsx.snap
  src/core/server/graph/schema/schema.graphql
Labels: 🚀 merge it!

#3283 [CORL-1478] Update counts and tags when commenting in QA mode
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/CreateCommentReplyMutation.ts
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/__snapshots__/PostCommentFormContainer.spec.tsx.snap
Labels: 🚀 merge it!

#3286 [CORL-1396] order story search results by relevance
  src/core/client/admin/routes/Moderate/ModerateSearchBar/Bar.tsx
  src/core/server/graph/loaders/Stories.ts
  src/core/server/models/comment/comment.ts
  src/core/server/models/helpers/query.ts
  src/core/server/models/story/story.ts
  src/locales/en-US/admin.ftl
Labels: 🚀 merge it!

#3289 [CORL-1460/CORL-1504] Fix slack configuration UI issues
  src/core/client/admin/routes/Configure/sections/Slack/SlackChannel.css
  src/core/client/admin/routes/Configure/sections/Slack/SlackChannel.tsx
  src/core/client/admin/routes/Configure/sections/Slack/SlackConfigContainer.tsx
Labels: 🚀 merge it!

#3270 [CORL-1461] show media in comment revisions
  src/core/client/admin/components/ModerateCard/CommentRevisionContainer.tsx
Labels: 🚀 merge it!

#3285 [CORL-1507] pass user drawer setID callback down to components
  src/core/client/admin/components/UserHistoryDrawer/Tabs.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawer.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerAllComments.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerAllCommentsQuery.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerContainer.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerQuery.tsx
  src/core/client/admin/routes/Community/UserTable.tsx
  src/core/client/admin/routes/Moderate/Queue/Queue.tsx
  src/core/client/admin/routes/Moderate/Queue/__snapshots__/Queue.spec.tsx.snap
Labels: 🚀 merge it!

#3290 [CORL-1512] font loading in nested path during dev
  src/core/client/admin/index.html
Labels: 🚀 merge it!

#3292 fix shape of optimistic response for comment replies
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/CreateCommentReplyMutation.ts
Labels: 🚀 merge it!

#3295 [CORL-1506] remove other statuses when banning a user
  src/core/client/admin/components/UserStatus/BanUserMutation.ts
  src/core/client/stream/tabs/Comments/Comment/UserBanPopover/BanUserMutation.ts
  src/core/client/stream/test/fixtures.ts
  src/core/server/services/users/users.ts
Labels: 🚀 merge it!

#3294 [CORL-1505] Explain missing usernames in user drawer
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerAllComments.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerContainer.css
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerContainer.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerRejectedComments.tsx
  src/core/client/admin/routes/Community/UserRow.css
  src/core/client/admin/routes/Community/UserRow.tsx
  src/locales/en-US/admin.ftl
Labels: 🚀 merge it!

#3298 Static files release fix
  .circleci/config.yml
Labels: 🚀 merge it!

#3300 Bump version 6.5.0
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3303 Comment Length Fix
  src/core/server/services/comments/pipeline/phases/commentLength.ts
Labels: 🚀 merge it!

#3299 [CORL-1528] JSONP endpoint for featured comments
  src/core/server/app/handlers/api/comment/featured.ts
  src/core/server/app/handlers/api/comment/index.ts
  src/core/server/app/handlers/api/index.ts
  src/core/server/app/router/api/comment.ts
  src/core/server/app/router/api/index.ts
  src/core/server/models/comment/comment.ts
Labels: 🚀 merge it!

#3308 [CORL-1532] GraphQL VS Code Support
  .graphqlconfig
  .vscode/extensions.json
  graphql.config.yml
  package-lock.json
  package.json
  relay-compiler-directives-v10.0.1.graphql
  scripts/compileRelay.ts
  scripts/generateSchemaTypes.js
  src/core/common/graphql/loadSchema.ts
Labels: 🚀 merge it!

#3311 [CORL-1442] add better error message when edit window expires on server
  src/core/common/errors.ts
  src/core/server/errors/index.ts
  src/core/server/errors/translations.ts
  src/core/server/locales/en-US/errors.ftl
  src/core/server/models/comment/comment.ts
Labels: 🚀 merge it!

#3302 [CORL-1449] Handle when actionCounts are unavailable
  src/core/client/admin/components/ModerateCard/ModerateCardContainer.tsx
Labels: 🚀 merge it!

#3313 [CORL-1517] Use relay to clear Done answered comments
  package-lock.json
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.css
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/RemoveAnswered.css
  src/core/client/stream/tabs/Comments/Comment/RemoveAnswered.tsx
  src/core/client/stream/tabs/Comments/Comment/RemoveAnsweredMutation.tsx
  src/core/client/stream/tabs/Comments/Comment/__snapshots__/CommentContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/ReplyList/ReplyList.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabContainer.tsx
Labels: 🚀 merge it!
