Repository coralproject/talk, pull requests merged in 2021-01, with the labels that each got.

#3244 [CORL-1365] Site Banning
  src/core/client/admin/components/ModerateCard/ModerateCardContainer.tsx
  src/core/client/admin/components/UserHistoryDrawer/AccountHistoryAction.tsx
  src/core/client/admin/components/UserHistoryDrawer/SiteBanAction.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserDrawerAccountHistory.css
  src/core/client/admin/components/UserHistoryDrawer/UserDrawerAccountHistory.tsx
  src/core/client/admin/components/UserStatus/BanModal.tsx
  src/core/client/admin/components/UserStatus/BanUserMutation.ts
  src/core/client/admin/components/UserStatus/RemoveUserBanMutation.ts
  src/core/client/admin/components/UserStatus/UserStatus.tsx
  src/core/client/admin/components/UserStatus/UserStatusChange.tsx
  src/core/client/admin/components/UserStatus/UserStatusChangeContainer.tsx
  src/core/client/admin/components/UserStatus/UserStatusContainer.tsx
  src/core/client/admin/components/UserStatus/UserStatusSitesListContainer.css
  src/core/client/admin/components/UserStatus/UserStatusSitesListContainer.tsx
  src/core/client/admin/components/UserStatus/UserStatusSitesListQuery.tsx
  src/core/client/admin/routes/Community/UserTableContainer.tsx
  src/core/client/admin/routes/Community/UserTableFilter.tsx
  src/core/client/framework/schema/custom.ts
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ModerationDropdown/ModerationDropdownContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/UserBanPopover/BanUserMutation.ts
  src/core/client/stream/tabs/Comments/Comment/UserBanPopover/UserBanPopoverContainer.tsx
  src/core/client/stream/tabs/Comments/helpers/getFlattenedReplyAncestorID.ts
  src/core/client/stream/tabs/Configure/Q&A/ExpertSelectionContainer.tsx
  src/core/client/test/helpers/fixture.ts
  src/core/common/errors.ts
  src/core/server/app/middleware/graphql/apolloServer.ts
  src/core/server/app/middleware/tenant.ts
  src/core/server/app/router/api/index.ts
  src/core/server/app/router/api/install.ts
  src/core/server/app/router/client.ts
  src/core/server/errors/index.ts
  src/core/server/errors/translations.ts
  src/core/server/graph/context.ts
  src/core/server/graph/directives/auth.ts
  src/core/server/graph/loaders/Users.ts
  src/core/server/graph/mutators/Users.ts
  src/core/server/graph/resolvers/BanStatus.ts
  src/core/server/graph/resolvers/BanStatusHistory.ts
  src/core/server/graph/resolvers/UserStatus.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/locales/en-US/errors.ftl
  src/core/server/models/user/helpers.ts
  src/core/server/models/user/user.ts
  src/core/server/services/comments/actions.ts
  src/core/server/services/users/users.ts
  src/core/server/stacks/createComment.ts
  src/core/server/stacks/editComment.ts
  src/core/server/types/express.ts
  src/locales/en-US/admin.ftl
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3364 [CORL-1592] Remove unused route
  src/core/server/app/router/client.ts
Labels: bug, 🚀 merge it!

#3359 [CORL-1589] CDN Headers
  .circleci/config.yml
Labels: bug, 🚀 merge it!

#3363 chore: upgrade sentry
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3365 Bugfix: accidental translation in server instead of client `experimental-tag`
  src/core/client/stream/tabs/Configure/Q&A/DisableQA.tsx
  src/core/client/stream/tabs/Configure/Q&A/EnableQA.tsx
  src/core/client/ui/components/v3/ExperimentalTag/ExperimentalTag.tsx
  src/core/server/locales/en-US/common.ftl
  src/core/server/locales/fi-FI/common.ftl
  src/core/server/locales/pl/common.ftl
  src/core/server/locales/pt-BR/common.ftl
  src/locales/en-US/common.ftl
  src/locales/en-US/stream.ftl
  src/locales/fi-FI/common.ftl
  src/locales/fi-FI/stream.ftl
  src/locales/fr-FR/stream.ftl
  src/locales/pl/common.ftl
  src/locales/pl/stream.ftl
  src/locales/pt-BR/common.ftl
  src/locales/pt-BR/stream.ftl
  src/locales/ru/stream.ftl
Labels: 🚀 merge it!

#3366 [CORL-1588] Added rating to featured comments
  src/core/client/stream/tabs/Comments/Stream/FeaturedComments/FeaturedCommentContainer.tsx
Labels: 🚀 merge it!

#3367 Add immutable to versioned assets
  .circleci/config.yml
Labels: 🚀 merge it!

#3370 fix: perspective api suggest score using model
  src/core/server/events/listeners/perspective.ts
  src/core/server/services/perspective/perspective.ts
Labels: 🚀 merge it!

#3368 Add new translations of version 6.6.2 for PT-BR
  src/locales/pt-BR/admin.ftl
  src/locales/pt-BR/framework.ftl
  src/locales/pt-BR/stream.ftl
Labels: 🚀 merge it!

#3374 [CORL-1598] Prevent duplicate ratings
  package-lock.json
  package.json
  src/core/common/errors.ts
  src/core/server/errors/index.ts
  src/core/server/errors/translations.ts
  src/core/server/locales/en-US/errors.ftl
  src/core/server/models/comment/comment.ts
  src/core/server/stacks/createComment.ts
Labels: bug, 🚀 merge it!

#3371 [CORL-1518] Show rejected comments as removed for staff in single conversation view
  src/core/client/stream/tabs/Comments/PermalinkView/PermalinkViewContainer.tsx
Labels: 🚀 merge it!

#3372 [CORL-1355] Place comment form at bottom when sorting by oldest on featured tab
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentsLinks/CommentsLinks.css
  src/core/client/stream/tabs/Comments/Stream/CommentsLinks/CommentsLinks.tsx
  src/core/client/stream/tabs/Comments/Stream/CommentsLinks/index.ts
  src/core/client/stream/tabs/Comments/Stream/FeaturedComments/FeaturedCommentsContainer.css
  src/core/client/stream/tabs/Comments/Stream/FeaturedComments/FeaturedCommentsContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
  src/core/client/stream/test/comments/stream/__snapshots__/loadMore.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderCommunityGuidelines.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderMessageBox.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/sortStream.spec.tsx.snap
Labels: 🚀 merge it!

#3351 [CORL-1526] Allow sorting moderation queues
  package-lock.json
  package.json
  src/core/client/account/App/App.tsx
  src/core/client/admin/App/App.tsx
  src/core/client/admin/App/GlobalNotification/useNotification.ts
  src/core/client/admin/components/ModerateCard/FeatureCommentMutation.ts
  src/core/client/admin/components/ModerateCard/ModerateCardContainer.tsx
  src/core/client/admin/constants.ts
  src/core/client/admin/helpers/getQueueConnection.ts
  src/core/client/admin/local/__snapshots__/initLocalState.spec.ts.snap
  src/core/client/admin/local/initLocalState.ts
  src/core/client/admin/local/local.graphql
  src/core/client/admin/mutations/ApproveCommentMutation.ts
  src/core/client/admin/mutations/RejectCommentMutation.ts
  src/core/client/admin/routeConfig.tsx
  src/core/client/admin/routes/Configure/NavigationWarningContainer.tsx
  src/core/client/admin/routes/Moderate/Moderate.tsx
  src/core/client/admin/routes/Moderate/Queue/ApprovedQueueRoute.tsx
  src/core/client/admin/routes/Moderate/Queue/Queue.spec.tsx
  src/core/client/admin/routes/Moderate/Queue/QueueCommentEnteredSubscription.tsx
  src/core/client/admin/routes/Moderate/Queue/QueueCommentLeftSubscription.tsx
  src/core/client/admin/routes/Moderate/Queue/QueueRoute.tsx
  src/core/client/admin/routes/Moderate/Queue/QueueSort/ChangeQueueSortMutation.ts
  src/core/client/admin/routes/Moderate/Queue/QueueSort/QueueSort.css
  src/core/client/admin/routes/Moderate/Queue/QueueSort/QueueSort.tsx
  src/core/client/admin/routes/Moderate/Queue/QueueViewNewMutation.tsx
  src/core/client/admin/routes/Moderate/Queue/RejectedQueueRoute.tsx
  src/core/client/admin/routes/Moderate/Queue/__snapshots__/Queue.spec.tsx.snap
  src/core/client/admin/routes/Moderate/Queue/index.ts
  src/core/client/admin/routes/Moderate/__snapshots__/Moderate.spec.tsx.snap
  src/core/client/admin/test/create.tsx
  src/core/client/admin/test/moderate/__snapshots__/regularQueue.spec.tsx.snap
  src/core/client/admin/test/moderate/__snapshots__/tabBar.spec.tsx.snap
  src/core/client/admin/test/moderate/regularQueue.spec.tsx
  src/core/client/admin/test/moderate/regularQueueLiveNewComments.spec.tsx
  src/core/client/admin/test/moderate/regularQueueLiveStatus.spec.tsx
  src/core/client/admin/test/moderate/rejectedQueue.spec.tsx
  src/core/client/framework/helpers/parseModerationOptions.ts
  src/core/client/framework/lib/router/createRouteConfig.ts
  src/core/client/framework/lib/router/createRouter.tsx
  src/core/client/framework/lib/router/index.ts
  src/core/client/framework/lib/router/withRouteConfig.ts
  src/core/client/framework/testHelpers/TransitionControl.tsx
  src/core/server/graph/loaders/Comments.ts
  src/core/server/graph/resolvers/ModerationQueue.ts
  src/core/server/graph/schema/schema.graphql
  src/locales/en-US/admin.ftl
  src/types/farce.d.ts
  src/types/found-relay.d.ts
  src/types/found.d.ts
Labels: 🚀 merge it!

#3379 [CORL-1531] Add tenant id to job logs
  src/core/server/queue/Task.ts
Labels: 🚀 merge it!

#3369 [CORL-1564] Add link to reply for flattened replies
  package-lock.json
  src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/ReplyCommentForm.spec.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/ReplyCommentFormContainer.spec.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/ReplyCommentFormContainer.tsx
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/__snapshots__/ReplyCommentForm.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/__snapshots__/ReplyCommentFormContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Comment/commentElementID.ts
  src/core/client/stream/tabs/Comments/helpers/getSubmitStatus.ts
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3373 Fix code around `useRefetch` and pagination `count` variable.
  src/core/client/admin/App/DecisionHistory/DecisionHistoryContainer.tsx
  src/core/client/admin/components/ConversationModal/ConversationModalContainer.tsx
  src/core/client/admin/components/ConversationModal/ConversationModalRepliesContainer.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerAllComments.tsx
  src/core/client/admin/components/UserHistoryDrawer/UserHistoryDrawerRejectedComments.tsx
  src/core/client/admin/components/UserRole/SiteModeratorModalSiteFieldContainer.tsx
  src/core/client/admin/components/UserStatus/UserStatusSitesListContainer.tsx
  src/core/client/admin/routes/Community/UserTableContainer.tsx
  src/core/client/admin/routes/Configure/sections/Organization/SitesConfigContainer.tsx
  src/core/client/admin/routes/Dashboard/DashboardContainer.tsx
  src/core/client/admin/routes/Moderate/Queue/ApprovedQueueRoute.tsx
  src/core/client/admin/routes/Moderate/Queue/QueueRoute.tsx
  src/core/client/admin/routes/Moderate/Queue/RejectedQueueRoute.tsx
  src/core/client/admin/routes/Moderate/SiteSelector/SiteSelectorContainer.tsx
  src/core/client/admin/routes/Stories/SiteFilter/SiteFilterContainer.tsx
  src/core/client/admin/routes/Stories/StoryTableContainer.tsx
  src/core/client/framework/lib/relay/useRefetch.ts
  src/core/client/stream/tabs/Comments/PermalinkView/ConversationThreadContainer.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AnsweredCommentsTab/AnsweredCommentsContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/FeaturedComments/FeaturedCommentsContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabContainer.tsx
  src/core/client/stream/tabs/Configure/Q&A/ExpertSelectionContainer.tsx
  src/core/client/stream/tabs/Profile/MyComments/CommentHistoryContainer.tsx
  src/core/client/stream/tabs/Profile/MyComments/HistoryCommentFooterContainer.tsx
Labels: 🚀 merge it!

#3382 Dependabot Support
  .github/dependabot.yml
Labels: 🚀 merge it!

#3388 Updated French translations : stream.ftl, account.ftl and framework.ftl
  src/locales/fr-FR/account.ftl
  src/locales/fr-FR/framework.ftl
  src/locales/fr-FR/stream.ftl
Labels: 🚀 merge it!

#3400 CSP Router Fix
  package-lock.json
  package.json
  src/core/server/app/router/api/index.ts
Labels: bug

#3375 [CORL-1535] Production Build with Profiler
  package.json
  src/core/build/config.ts
  src/core/build/createWebpackConfig.ts
  src/core/client/stream/index.html
Labels: 🚀 merge it!

#3406 Hotfix 6.7.2 - French translations
  package-lock.json
  package.json
  src/core/client/stream/tabs/Comments/Comment/PermalinkButton/PermalinkPopover.tsx
  src/locales/en-US/stream.ftl
  src/locales/fr-FR/account.ftl
  src/locales/fr-FR/framework.ftl
  src/locales/fr-FR/stream.ftl
Labels: 🚀 merge it!
