Repository coralproject/talk, pull requests merged in 2021-02, with the labels that each got.

#3405 Remove deprecated workaround hideForwardRef
  src/core/client/admin/components/ModerateCard/ModeratedByContainer.spec.tsx
  src/core/client/admin/components/ModerateCard/__snapshots__/ModeratedByContainer.spec.tsx.snap
  src/core/client/framework/lib/relay/withFragmentContainer.ts
  src/core/client/framework/lib/relay/withPaginationContainer.ts
  src/core/client/framework/lib/relay/withRefetchContainer.ts
Labels: 🚀 merge it!

#3409 [CHORE] Provide a hook version of withStyles called useStyles
  src/core/client/ui/components/v2/BaseButton/BaseButton.tsx
  src/core/client/ui/components/v2/Button/Button.tsx
  src/core/client/ui/components/v2/Button/__snapshots__/Button.spec.tsx.snap
  src/core/client/ui/components/v2/Dropdown/Button.tsx
  src/core/client/ui/components/v2/Dropdown/__snapshots__/Button.spec.tsx.snap
  src/core/client/ui/components/v2/Dropdown/__snapshots__/Dropdown.spec.tsx.snap
  src/core/client/ui/components/v3/Button/Button.tsx
  src/core/client/ui/hocs/withStyles.ts
  src/core/client/ui/hooks/index.ts
  src/core/client/ui/hooks/useStyles.ts
Labels: 🚀 merge it!

#3420 [CORL-1629] SSO Fix
  src/core/server/app/middleware/passport/strategies/verifiers/sso.ts
  src/core/server/models/user/user.ts
Labels: bug, 🚀 merge it!

#3389 [CORL-1131] Add feature flag to disable live updates at tenant level
  src/core/client/framework/hooks/useLive.ts
  src/core/server/graph/resolvers/LiveConfiguration.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/services/stories/index.ts
Labels: 🚀 merge it!

#3397 [CORL-1607] Optimize Rendering Performance of Lists
  package-lock.json
  package.json
  relay-compiler-directives-v10.0.1.graphql
  src/core/client/admin/routes/Moderate/Queue/Queue.tsx
  src/core/client/framework/hooks/index.ts
  src/core/client/framework/hooks/useEffectWhenChanged.ts
  src/core/client/framework/hooks/useMemoizer.ts
  src/core/client/stream/tabs/Comments/Comment/ReplyCommentForm/CreateCommentReplyMutation.ts
  src/core/client/stream/tabs/Comments/ReplyList/LocalReplyListContainer.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyList.css
  src/core/client/stream/tabs/Comments/ReplyList/ReplyList.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListCommentContainer.css
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListCommentContainer.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.spec.tsx
  src/core/client/stream/tabs/Comments/ReplyList/ReplyListContainer.tsx
  src/core/client/stream/tabs/Comments/ReplyList/__snapshots__/ReplyList.spec.tsx.snap
  src/core/client/stream/tabs/Comments/ReplyList/__snapshots__/ReplyListContainer.spec.tsx.snap
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabCommentContainer.css
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabCommentContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.css
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/CommentEnteredSubscription.tsx
  src/core/client/stream/tabs/Comments/Stream/AnsweredCommentsTab/AnsweredCommentContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/AnsweredCommentsTab/AnsweredCommentsContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/FeaturedComments/FeaturedCommentContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/FeaturedComments/FeaturedCommentsContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabCommentContainer.css
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabCommentContainer.tsx
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabContainer.css
  src/core/client/stream/tabs/Comments/Stream/UnansweredCommentsTab/UnansweredCommentsTabContainer.tsx
  src/core/client/stream/test/comments/stream/__snapshots__/loadMore.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderCommunityGuidelines.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/sortStream.spec.tsx.snap
Labels: 🚀 merge it!

#3414 [CORL-1616/18/28] Fix typo-ed or missing translation keys in admin/stream.ftl
  src/locales/en-US/admin.ftl
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3417 [CORL-1620] Catch errors in external media same as other oEmbed handlers
  src/core/server/services/comments/media.ts
Labels: 🚀 merge it!

#3407 [CORL-1603] On small screens, bump the select sort text size
  src/core/client/stream/tabs/Comments/Stream/SortMenu.css
Labels: 🚀 merge it!

#3404 Add recent 6.7.1 translations for PT-BR
  src/core/server/locales/pt-BR/errors.ftl
  src/locales/pt-BR/admin.ftl
  src/locales/pt-BR/stream.ftl
Labels: 🚀 merge it!

#3421 bump to 6.8.0
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3390 Updated RU translation: added permalink copy text
  src/locales/ru/stream.ftl
Labels: 🚀 merge it!

#3403 german (de-CH) translations (none formal (du) version)
  src/core/client/admin/test/configure/__snapshots__/general.spec.tsx.snap
  src/core/common/helpers/i18n/locales.ts
  src/locales/de-CH/account.ftl
  src/locales/de-CH/auth.ftl
  src/locales/de-CH/common.ftl
  src/locales/de-CH/framework.ftl
  src/locales/de-CH/install.ftl
  src/locales/de-CH/stream.ftl
  src/locales/de/common.ftl
Labels: 🚀 merge it!

#3424 Se tradujo text para usuario baneado, advertencias y suspenciones
  src/locales/es/stream.ftl
Labels: i18n, 🚀 merge it!

#3429 Dockerfile.onbuild Permission Fix
  Dockerfile.onbuild
Labels: bug, v4

#3426 [CORL-1599] Font descenders cutting off in ff
  src/core/client/stream/tabs/Comments/Stream/SortMenu.css
  src/core/client/stream/tabs/Comments/Stream/SortMenu.tsx
  src/core/client/stream/test/comments/featured/__snapshots__/renderFeaturedStream.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderCommunityGuidelines.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderMessageBox.spec.tsx.snap
  src/core/client/stream/test/comments/stream/__snapshots__/renderStream.spec.tsx.snap
  src/core/client/ui/components/v2/SelectField/SelectField.css
Labels: 🚀 merge it!

#3443 [CORL-1656] i18n Error Fixes
  src/core/common/errors.ts
  src/core/server/errors/index.ts
  src/core/server/errors/translations.ts
  src/core/server/locales/en-US/errors.ftl
  src/core/server/models/comment/comment.ts
  src/core/server/services/comments/moderation/moderate.ts
  src/core/server/stacks/helpers/retrieveParent.ts
Labels: bug, 🚀 merge it!

#3435 Add new translation to admin and stream ftl
  src/locales/es/admin.ftl
  src/locales/es/stream.ftl
Labels: 🚀 merge it!

#3446 de-CH email translations and fixes
  src/core/server/locales/de-CH/common.ftl
  src/core/server/locales/de-CH/email.ftl
  src/locales/de-CH/account.ftl
  src/locales/de-CH/auth.ftl
  src/locales/de-CH/common.ftl
  src/locales/de-CH/framework.ftl
  src/locales/de-CH/stream.ftl
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3447 update version to 6.8.1
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3444 [CORL-1004] Upgrade dataloader
  package-lock.json
  package.json
  src/core/server/app/handlers/api/comment/featured.ts
  src/core/server/helpers/dataloader.ts
  src/core/server/models/comment/comment.ts
  src/core/server/models/site/index.ts
  src/core/server/models/story/story.ts
  src/core/server/models/tenant/tenant.ts
  src/core/server/models/user/user.ts
  src/core/server/services/notifications/categories/reply.ts
  src/core/server/services/notifications/categories/staffReply.ts
  src/core/server/services/users/download/download.ts
Labels: 🚀 merge it!

#3450 add new spanish translate
  src/locales/es/admin.ftl
Labels: 🚀 merge it!

#3427 [CORL-1632] Allow basic auth config for scraper jobs
  src/core/client/admin/routes/Configure/sections/Advanced/StoryCreationConfig.tsx
  src/core/client/admin/test/configure/__snapshots__/advanced.spec.tsx.snap
  src/core/client/admin/test/fixtures.ts
  src/core/server/graph/resolvers/Settings.ts
  src/core/server/graph/resolvers/StoryScrapingConfiguration.ts
  src/core/server/graph/resolvers/index.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/models/settings/settings.ts
  src/core/server/models/tenant/tenant.ts
  src/core/server/services/stories/scraper/scraper.ts
  src/locales/en-US/admin.ftl
Labels: 🚀 merge it!

#3460 Dashboard translation to spanish
  src/locales/es/admin.ftl
Labels: 🚀 merge it!

#3456 [WATCHER] Log reason that triggered a watch action
  scripts/watcher/watch.ts
Labels: 🚀 merge it!

#3465 [CORL-1666] CircleCI Improvements
  .circleci/config.yml
  .github/dependabot.yml
Labels: 🚀 merge it!
