Repository coralproject/talk, pull requests merged in 2021-04, with the labels that each got.

#3480 [CORL-1696] SMTP Meta
  src/core/server/graph/schema/schema.graphql
  src/core/server/queue/tasks/mailer/index.ts
  src/core/server/queue/tasks/mailer/processor.ts
Labels: 🚀 merge it!

#3431 [CORL-1649] Bugfix: Comment draft deleted on login or registration
  src/core/client/framework/hooks/index.ts
  src/core/client/framework/hooks/usePersistedLocalState.ts
  src/core/client/framework/hooks/usePersistedSessionState.ts
  src/core/client/framework/hooks/usePersistedState.ts
  src/core/client/framework/lib/bootstrap/createManaged.tsx
  src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
Labels: 🚀 merge it!

#3474 [CORL-1685] Lowercase Email Addresses
  src/core/server/app/authenticators/facebook/facebook.ts
  src/core/server/app/authenticators/google/google.ts
  src/core/server/models/user/user.ts
  src/core/server/services/oidc/oidc.spec.ts
  src/core/server/services/oidc/oidc.ts
Labels: bug, 🚀 merge it!

#3489 bump to 6.9.0
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3487 Fixed typo in url for translations
  CONTRIBUTING.md
Labels: 🚀 merge it!

#3497 [CORL-1710] Scraper Authentication Fix
  src/core/server/services/stories/scraper/scraper.ts
Labels: bug

#3507 Live Chat: Mutation fixes and cleanup
  package-lock.json
  src/core/client/stream/local/__snapshots__/initLocalState.spec.ts.snap
  src/core/client/stream/tabs/Live/LiveChatContainer.tsx
  src/core/client/stream/tabs/Live/LiveConversation/LiveCommentReplies/LiveReplyContainer.tsx
  src/core/client/stream/tabs/Live/LiveConversation/LiveConversationContainer.tsx
  src/core/client/stream/tabs/Live/LiveConversation/LiveCreateCommentReplyMutation.tsx
  src/core/client/stream/tabs/Live/LiveCreateCommentMutation.tsx
Labels: 🚀 merge it!

#3512 CORL-1702: List size does not adapt when the height of a comment changes
  package-lock.json
  package.json
Labels: 🚀 merge it!

#3515 Finnish translations updated to 6.9.0
  src/core/server/locales/fi-FI/errors.ftl
  src/locales/fi-FI/framework.ftl
  src/locales/fi-FI/stream.ftl
Labels: 🚀 merge it!

#3493 [CORL-1709] adding af-za translations
  src/core/client/admin/test/configure/__snapshots__/general.spec.tsx.snap
  src/core/common/helpers/i18n/locales.ts
  src/locales/af-ZA/admin.ftl
  src/locales/af-ZA/framework.ftl
  src/locales/af-ZA/stream.ftl
Labels: i18n, 🚀 merge it!

#3519 [CORL-1739] Live Chat: Tombstone rejected comments with subscription
  src/core/client/stream/tabs/Live/LiveChatContainer.tsx
  src/core/client/stream/tabs/Live/LiveComment/LiveCommentContainer.tsx
  src/core/client/stream/tabs/Live/LiveCommentRejectedSubscription.tsx
  src/core/server/events/events.ts
  src/core/server/events/listeners/analytics.ts
  src/core/server/events/listeners/subscription.ts
  src/core/server/events/types.ts
  src/core/server/graph/resolvers/Comment.ts
  src/core/server/graph/resolvers/CommentCreatedPayload.ts
  src/core/server/graph/resolvers/CommentEditedPayload.ts
  src/core/server/graph/resolvers/CommentEnteredModerationQueuePayload.ts
  src/core/server/graph/resolvers/CommentEnteredPayload.ts
  src/core/server/graph/resolvers/CommentLeftModerationQueuePayload.ts
  src/core/server/graph/resolvers/CommentRejectedPayload.ts
  src/core/server/graph/resolvers/CommentReleasedPayload.ts
  src/core/server/graph/resolvers/CommentReplyCreatedPayload.ts
  src/core/server/graph/resolvers/CommentStatusUpdatedPayload.ts
  src/core/server/graph/resolvers/Subscription/commentRejected.ts
  src/core/server/graph/resolvers/Subscription/index.ts
  src/core/server/graph/resolvers/Subscription/types.ts
  src/core/server/graph/resolvers/index.ts
  src/core/server/graph/schema/schema.graphql
  src/core/server/services/events/comments.ts
  src/locales/en-US/stream.ftl
Labels: 🚀 merge it!

#3501 Expanded Feature Flag Filter
  src/core/server/graph/mutators/Settings.ts
Labels: bug, 🚀 merge it!

#3475 Se añadio nueva traduccion al archivo /es/stream.ftl
  src/locales/es/stream.ftl
Labels: 🚀 merge it!

#3439 Auto focus first input field on Sign In and Sign Up popups
  src/core/client/auth/components/EmailField.tsx
  src/core/client/auth/views/SignIn/SignInWithEmail.tsx
  src/core/client/auth/views/SignUp/SignUpWithEmail.tsx
Labels: 🚀 merge it!

#3529 Rename translation key
  src/locales/da/stream.ftl
  src/locales/nl-NL/stream.ftl
  src/locales/ro/stream.ftl
  src/locales/sv/stream.ftl
Labels: 🚀 merge it!
